/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.PassengerTerm;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A code that is used to categorize reasons for a train not being on schedule
 */
@JsonPropertyOrder({
  CategoryCode.JSON_PROPERTY_PASSENGER_TERM,
  CategoryCode.JSON_PROPERTY_CATEGORY_CODE,
  CategoryCode.JSON_PROPERTY_CATEGORY_NAME,
  CategoryCode.JSON_PROPERTY_VALID_FROM,
  CategoryCode.JSON_PROPERTY_VALID_TO,
  CategoryCode.JSON_PROPERTY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class CategoryCode {
  public static final String JSON_PROPERTY_PASSENGER_TERM = "passengerTerm";
  private PassengerTerm passengerTerm;

  public static final String JSON_PROPERTY_CATEGORY_CODE = "categoryCode";
  private String categoryCode;

  public static final String JSON_PROPERTY_CATEGORY_NAME = "categoryName";
  private String categoryName;

  public static final String JSON_PROPERTY_VALID_FROM = "validFrom";
  private LocalDate validFrom;

  public static final String JSON_PROPERTY_VALID_TO = "validTo";
  private LocalDate validTo;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public CategoryCode() {
  }

  public CategoryCode passengerTerm(PassengerTerm passengerTerm) {
    
    this.passengerTerm = passengerTerm;
    return this;
  }

   /**
   * Get passengerTerm
   * @return passengerTerm
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSENGER_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PassengerTerm getPassengerTerm() {
    return passengerTerm;
  }


  @JsonProperty(JSON_PROPERTY_PASSENGER_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassengerTerm(PassengerTerm passengerTerm) {
    this.passengerTerm = passengerTerm;
  }


  public CategoryCode categoryCode(String categoryCode) {
    
    this.categoryCode = categoryCode;
    return this;
  }

   /**
   * Official code
   * @return categoryCode
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCategoryCode() {
    return categoryCode;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }


  public CategoryCode categoryName(String categoryName) {
    
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Official name
   * @return categoryName
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCategoryName() {
    return categoryName;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }


  public CategoryCode validFrom(LocalDate validFrom) {
    
    this.validFrom = validFrom;
    return this;
  }

   /**
   * Start date when this code is used
   * @return validFrom
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getValidFrom() {
    return validFrom;
  }


  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidFrom(LocalDate validFrom) {
    this.validFrom = validFrom;
  }


  public CategoryCode validTo(LocalDate validTo) {
    
    this.validTo = validTo;
    return this;
  }

   /**
   * End date when this code is used. Empty means category is used until further notice
   * @return validTo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getValidTo() {
    return validTo;
  }


  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidTo(LocalDate validTo) {
    this.validTo = validTo;
  }


  public CategoryCode id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryCode categoryCode = (CategoryCode) o;
    return Objects.equals(this.passengerTerm, categoryCode.passengerTerm) &&
        Objects.equals(this.categoryCode, categoryCode.categoryCode) &&
        Objects.equals(this.categoryName, categoryCode.categoryName) &&
        Objects.equals(this.validFrom, categoryCode.validFrom) &&
        Objects.equals(this.validTo, categoryCode.validTo) &&
        Objects.equals(this.id, categoryCode.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passengerTerm, categoryCode, categoryName, validFrom, validTo, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryCode {\n");
    sb.append("    passengerTerm: ").append(toIndentedString(passengerTerm)).append("\n");
    sb.append("    categoryCode: ").append(toIndentedString(categoryCode)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

