/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.PassengerTerm;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Details why a train is not on schedule. Train-responses only have ids and codes populated.
 */
@JsonPropertyOrder({
  Cause.JSON_PROPERTY_PASSENGER_TERM,
  Cause.JSON_PROPERTY_CATEGORY_CODE,
  Cause.JSON_PROPERTY_CATEGORY_NAME,
  Cause.JSON_PROPERTY_VALID_FROM,
  Cause.JSON_PROPERTY_VALID_TO,
  Cause.JSON_PROPERTY_ID,
  Cause.JSON_PROPERTY_DETAILED_CATEGORY_CODE,
  Cause.JSON_PROPERTY_DETAILED_CATEGORY_NAME,
  Cause.JSON_PROPERTY_THIRD_CATEGORY_CODE,
  Cause.JSON_PROPERTY_THIRD_CATEGORY_NAME,
  Cause.JSON_PROPERTY_DESCRIPTION,
  Cause.JSON_PROPERTY_CATEGORY_CODE_ID,
  Cause.JSON_PROPERTY_DETAILED_CATEGORY_CODE_ID,
  Cause.JSON_PROPERTY_THIRD_CATEGORY_CODE_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class Cause {
  public static final String JSON_PROPERTY_PASSENGER_TERM = "passengerTerm";
  private PassengerTerm passengerTerm;

  public static final String JSON_PROPERTY_CATEGORY_CODE = "categoryCode";
  private String categoryCode;

  public static final String JSON_PROPERTY_CATEGORY_NAME = "categoryName";
  private String categoryName;

  public static final String JSON_PROPERTY_VALID_FROM = "validFrom";
  private LocalDate validFrom;

  public static final String JSON_PROPERTY_VALID_TO = "validTo";
  private LocalDate validTo;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_DETAILED_CATEGORY_CODE = "detailedCategoryCode";
  private String detailedCategoryCode;

  public static final String JSON_PROPERTY_DETAILED_CATEGORY_NAME = "detailedCategoryName";
  private String detailedCategoryName;

  public static final String JSON_PROPERTY_THIRD_CATEGORY_CODE = "thirdCategoryCode";
  private String thirdCategoryCode;

  public static final String JSON_PROPERTY_THIRD_CATEGORY_NAME = "thirdCategoryName";
  private String thirdCategoryName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_CATEGORY_CODE_ID = "categoryCodeId";
  private Integer categoryCodeId;

  public static final String JSON_PROPERTY_DETAILED_CATEGORY_CODE_ID = "detailedCategoryCodeId";
  private Integer detailedCategoryCodeId;

  public static final String JSON_PROPERTY_THIRD_CATEGORY_CODE_ID = "thirdCategoryCodeId";
  private Integer thirdCategoryCodeId;

  public Cause() {
  }

  public Cause passengerTerm(PassengerTerm passengerTerm) {
    
    this.passengerTerm = passengerTerm;
    return this;
  }

   /**
   * Get passengerTerm
   * @return passengerTerm
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSENGER_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PassengerTerm getPassengerTerm() {
    return passengerTerm;
  }


  @JsonProperty(JSON_PROPERTY_PASSENGER_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassengerTerm(PassengerTerm passengerTerm) {
    this.passengerTerm = passengerTerm;
  }


  public Cause categoryCode(String categoryCode) {
    
    this.categoryCode = categoryCode;
    return this;
  }

   /**
   * Official code
   * @return categoryCode
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCategoryCode() {
    return categoryCode;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }


  public Cause categoryName(String categoryName) {
    
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Official name
   * @return categoryName
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCategoryName() {
    return categoryName;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }


  public Cause validFrom(LocalDate validFrom) {
    
    this.validFrom = validFrom;
    return this;
  }

   /**
   * Start date when this category code is used
   * @return validFrom
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getValidFrom() {
    return validFrom;
  }


  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidFrom(LocalDate validFrom) {
    this.validFrom = validFrom;
  }


  public Cause validTo(LocalDate validTo) {
    
    this.validTo = validTo;
    return this;
  }

   /**
   * End date when this code is used. Empty means category is used until further notice
   * @return validTo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getValidTo() {
    return validTo;
  }


  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidTo(LocalDate validTo) {
    this.validTo = validTo;
  }


  public Cause id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public Cause detailedCategoryCode(String detailedCategoryCode) {
    
    this.detailedCategoryCode = detailedCategoryCode;
    return this;
  }

   /**
   * Get detailedCategoryCode
   * @return detailedCategoryCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDetailedCategoryCode() {
    return detailedCategoryCode;
  }


  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetailedCategoryCode(String detailedCategoryCode) {
    this.detailedCategoryCode = detailedCategoryCode;
  }


  public Cause detailedCategoryName(String detailedCategoryName) {
    
    this.detailedCategoryName = detailedCategoryName;
    return this;
  }

   /**
   * Get detailedCategoryName
   * @return detailedCategoryName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDetailedCategoryName() {
    return detailedCategoryName;
  }


  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetailedCategoryName(String detailedCategoryName) {
    this.detailedCategoryName = detailedCategoryName;
  }


  public Cause thirdCategoryCode(String thirdCategoryCode) {
    
    this.thirdCategoryCode = thirdCategoryCode;
    return this;
  }

   /**
   * Get thirdCategoryCode
   * @return thirdCategoryCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getThirdCategoryCode() {
    return thirdCategoryCode;
  }


  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThirdCategoryCode(String thirdCategoryCode) {
    this.thirdCategoryCode = thirdCategoryCode;
  }


  public Cause thirdCategoryName(String thirdCategoryName) {
    
    this.thirdCategoryName = thirdCategoryName;
    return this;
  }

   /**
   * Get thirdCategoryName
   * @return thirdCategoryName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getThirdCategoryName() {
    return thirdCategoryName;
  }


  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThirdCategoryName(String thirdCategoryName) {
    this.thirdCategoryName = thirdCategoryName;
  }


  public Cause description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Detailed description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public Cause categoryCodeId(Integer categoryCodeId) {
    
    this.categoryCodeId = categoryCodeId;
    return this;
  }

   /**
   * Get categoryCodeId
   * @return categoryCodeId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CATEGORY_CODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCategoryCodeId() {
    return categoryCodeId;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY_CODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategoryCodeId(Integer categoryCodeId) {
    this.categoryCodeId = categoryCodeId;
  }


  public Cause detailedCategoryCodeId(Integer detailedCategoryCodeId) {
    
    this.detailedCategoryCodeId = detailedCategoryCodeId;
    return this;
  }

   /**
   * Get detailedCategoryCodeId
   * @return detailedCategoryCodeId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_CODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDetailedCategoryCodeId() {
    return detailedCategoryCodeId;
  }


  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_CODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetailedCategoryCodeId(Integer detailedCategoryCodeId) {
    this.detailedCategoryCodeId = detailedCategoryCodeId;
  }


  public Cause thirdCategoryCodeId(Integer thirdCategoryCodeId) {
    
    this.thirdCategoryCodeId = thirdCategoryCodeId;
    return this;
  }

   /**
   * Get thirdCategoryCodeId
   * @return thirdCategoryCodeId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_CODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getThirdCategoryCodeId() {
    return thirdCategoryCodeId;
  }


  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_CODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThirdCategoryCodeId(Integer thirdCategoryCodeId) {
    this.thirdCategoryCodeId = thirdCategoryCodeId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cause cause = (Cause) o;
    return Objects.equals(this.passengerTerm, cause.passengerTerm) &&
        Objects.equals(this.categoryCode, cause.categoryCode) &&
        Objects.equals(this.categoryName, cause.categoryName) &&
        Objects.equals(this.validFrom, cause.validFrom) &&
        Objects.equals(this.validTo, cause.validTo) &&
        Objects.equals(this.id, cause.id) &&
        Objects.equals(this.detailedCategoryCode, cause.detailedCategoryCode) &&
        Objects.equals(this.detailedCategoryName, cause.detailedCategoryName) &&
        Objects.equals(this.thirdCategoryCode, cause.thirdCategoryCode) &&
        Objects.equals(this.thirdCategoryName, cause.thirdCategoryName) &&
        Objects.equals(this.description, cause.description) &&
        Objects.equals(this.categoryCodeId, cause.categoryCodeId) &&
        Objects.equals(this.detailedCategoryCodeId, cause.detailedCategoryCodeId) &&
        Objects.equals(this.thirdCategoryCodeId, cause.thirdCategoryCodeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passengerTerm, categoryCode, categoryName, validFrom, validTo, id, detailedCategoryCode, detailedCategoryName, thirdCategoryCode, thirdCategoryName, description, categoryCodeId, detailedCategoryCodeId, thirdCategoryCodeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cause {\n");
    sb.append("    passengerTerm: ").append(toIndentedString(passengerTerm)).append("\n");
    sb.append("    categoryCode: ").append(toIndentedString(categoryCode)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    detailedCategoryCode: ").append(toIndentedString(detailedCategoryCode)).append("\n");
    sb.append("    detailedCategoryName: ").append(toIndentedString(detailedCategoryName)).append("\n");
    sb.append("    thirdCategoryCode: ").append(toIndentedString(thirdCategoryCode)).append("\n");
    sb.append("    thirdCategoryName: ").append(toIndentedString(thirdCategoryName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    categoryCodeId: ").append(toIndentedString(categoryCodeId)).append("\n");
    sb.append("    detailedCategoryCodeId: ").append(toIndentedString(detailedCategoryCodeId)).append("\n");
    sb.append("    thirdCategoryCodeId: ").append(toIndentedString(thirdCategoryCodeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

