/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Describes a point in a trains schedule where its composition changes
 */
@JsonPropertyOrder({
  CompositionTimeTableRow.JSON_PROPERTY_STATION_SHORT_CODE,
  CompositionTimeTableRow.JSON_PROPERTY_STATION_U_I_C_CODE,
  CompositionTimeTableRow.JSON_PROPERTY_COUNTRY_CODE,
  CompositionTimeTableRow.JSON_PROPERTY_TYPE,
  CompositionTimeTableRow.JSON_PROPERTY_SCHEDULED_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class CompositionTimeTableRow {
  public static final String JSON_PROPERTY_STATION_SHORT_CODE = "stationShortCode";
  private String stationShortCode;

  public static final String JSON_PROPERTY_STATION_U_I_C_CODE = "stationUICCode";
  private Integer stationUICCode;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "countryCode";
  private String countryCode;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ARRIVAL("ARRIVAL"),
    
    DEPARTURE("DEPARTURE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_SCHEDULED_TIME = "scheduledTime";
  private OffsetDateTime scheduledTime;

  public CompositionTimeTableRow() {
  }

  public CompositionTimeTableRow stationShortCode(String stationShortCode) {
    
    this.stationShortCode = stationShortCode;
    return this;
  }

   /**
   * Get stationShortCode
   * @return stationShortCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStationShortCode() {
    return stationShortCode;
  }


  @JsonProperty(JSON_PROPERTY_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStationShortCode(String stationShortCode) {
    this.stationShortCode = stationShortCode;
  }


  public CompositionTimeTableRow stationUICCode(Integer stationUICCode) {
    
    this.stationUICCode = stationUICCode;
    return this;
  }

   /**
   * Get stationUICCode
   * @return stationUICCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStationUICCode() {
    return stationUICCode;
  }


  @JsonProperty(JSON_PROPERTY_STATION_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStationUICCode(Integer stationUICCode) {
    this.stationUICCode = stationUICCode;
  }


  public CompositionTimeTableRow countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public CompositionTimeTableRow type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public CompositionTimeTableRow scheduledTime(OffsetDateTime scheduledTime) {
    
    this.scheduledTime = scheduledTime;
    return this;
  }

   /**
   * Get scheduledTime
   * @return scheduledTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEDULED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getScheduledTime() {
    return scheduledTime;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledTime(OffsetDateTime scheduledTime) {
    this.scheduledTime = scheduledTime;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompositionTimeTableRow compositionTimeTableRow = (CompositionTimeTableRow) o;
    return Objects.equals(this.stationShortCode, compositionTimeTableRow.stationShortCode) &&
        Objects.equals(this.stationUICCode, compositionTimeTableRow.stationUICCode) &&
        Objects.equals(this.countryCode, compositionTimeTableRow.countryCode) &&
        Objects.equals(this.type, compositionTimeTableRow.type) &&
        Objects.equals(this.scheduledTime, compositionTimeTableRow.scheduledTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stationShortCode, stationUICCode, countryCode, type, scheduledTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompositionTimeTableRow {\n");
    sb.append("    stationShortCode: ").append(toIndentedString(stationShortCode)).append("\n");
    sb.append("    stationUICCode: ").append(toIndentedString(stationUICCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    scheduledTime: ").append(toIndentedString(scheduledTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

