/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import fi.digitraffic.traingraph.model.JourneySection;
import java.time.LocalDate;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Describes train&#39;s locomotives and wagons
 */
@JsonPropertyOrder({
  Composition.JSON_PROPERTY_TRAIN_NUMBER,
  Composition.JSON_PROPERTY_DEPARTURE_DATE,
  Composition.JSON_PROPERTY_OPERATOR_U_I_C_CODE,
  Composition.JSON_PROPERTY_OPERATOR_SHORT_CODE,
  Composition.JSON_PROPERTY_TRAIN_CATEGORY,
  Composition.JSON_PROPERTY_TRAIN_TYPE,
  Composition.JSON_PROPERTY_VERSION,
  Composition.JSON_PROPERTY_JOURNEY_SECTIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class Composition {
  public static final String JSON_PROPERTY_TRAIN_NUMBER = "trainNumber";
  private Long trainNumber;

  public static final String JSON_PROPERTY_DEPARTURE_DATE = "departureDate";
  private LocalDate departureDate;

  public static final String JSON_PROPERTY_OPERATOR_U_I_C_CODE = "operatorUICCode";
  private Integer operatorUICCode;

  public static final String JSON_PROPERTY_OPERATOR_SHORT_CODE = "operatorShortCode";
  private String operatorShortCode;

  public static final String JSON_PROPERTY_TRAIN_CATEGORY = "trainCategory";
  private String trainCategory;

  public static final String JSON_PROPERTY_TRAIN_TYPE = "trainType";
  private String trainType;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_JOURNEY_SECTIONS = "journeySections";
  private Set<JourneySection> journeySections;

  public Composition() {
  }

  public Composition trainNumber(Long trainNumber) {
    
    this.trainNumber = trainNumber;
    return this;
  }

   /**
   * Identifies the train inside a single departure date
   * @return trainNumber
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTrainNumber() {
    return trainNumber;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainNumber(Long trainNumber) {
    this.trainNumber = trainNumber;
  }


  public Composition departureDate(LocalDate departureDate) {
    
    this.departureDate = departureDate;
    return this;
  }

   /**
   * Date of the train&#39;s first departure
   * @return departureDate
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getDepartureDate() {
    return departureDate;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDepartureDate(LocalDate departureDate) {
    this.departureDate = departureDate;
  }


  public Composition operatorUICCode(Integer operatorUICCode) {
    
    this.operatorUICCode = operatorUICCode;
    return this;
  }

   /**
   * Official UIC code of the operator
   * @return operatorUICCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOperatorUICCode() {
    return operatorUICCode;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatorUICCode(Integer operatorUICCode) {
    this.operatorUICCode = operatorUICCode;
  }


  public Composition operatorShortCode(String operatorShortCode) {
    
    this.operatorShortCode = operatorShortCode;
    return this;
  }

   /**
   * Short code of the operator
   * @return operatorShortCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperatorShortCode() {
    return operatorShortCode;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatorShortCode(String operatorShortCode) {
    this.operatorShortCode = operatorShortCode;
  }


  public Composition trainCategory(String trainCategory) {
    
    this.trainCategory = trainCategory;
    return this;
  }

   /**
   * Get trainCategory
   * @return trainCategory
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRAIN_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTrainCategory() {
    return trainCategory;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainCategory(String trainCategory) {
    this.trainCategory = trainCategory;
  }


  public Composition trainType(String trainType) {
    
    this.trainType = trainType;
    return this;
  }

   /**
   * Get trainType
   * @return trainType
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRAIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTrainType() {
    return trainType;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainType(String trainType) {
    this.trainType = trainType;
  }


  public Composition version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * When was this data last modified
   * @return version
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(Long version) {
    this.version = version;
  }


  public Composition journeySections(Set<JourneySection> journeySections) {
    
    this.journeySections = journeySections;
    return this;
  }

  public Composition addJourneySectionsItem(JourneySection journeySectionsItem) {
    if (this.journeySections == null) {
      this.journeySections = new LinkedHashSet<>();
    }
    this.journeySections.add(journeySectionsItem);
    return this;
  }

   /**
   * Get journeySections
   * @return journeySections
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOURNEY_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<JourneySection> getJourneySections() {
    return journeySections;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_JOURNEY_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJourneySections(Set<JourneySection> journeySections) {
    this.journeySections = journeySections;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Composition composition = (Composition) o;
    return Objects.equals(this.trainNumber, composition.trainNumber) &&
        Objects.equals(this.departureDate, composition.departureDate) &&
        Objects.equals(this.operatorUICCode, composition.operatorUICCode) &&
        Objects.equals(this.operatorShortCode, composition.operatorShortCode) &&
        Objects.equals(this.trainCategory, composition.trainCategory) &&
        Objects.equals(this.trainType, composition.trainType) &&
        Objects.equals(this.version, composition.version) &&
        Objects.equals(this.journeySections, composition.journeySections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trainNumber, departureDate, operatorUICCode, operatorShortCode, trainCategory, trainType, version, journeySections);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Composition {\n");
    sb.append("    trainNumber: ").append(toIndentedString(trainNumber)).append("\n");
    sb.append("    departureDate: ").append(toIndentedString(departureDate)).append("\n");
    sb.append("    operatorUICCode: ").append(toIndentedString(operatorUICCode)).append("\n");
    sb.append("    operatorShortCode: ").append(toIndentedString(operatorShortCode)).append("\n");
    sb.append("    trainCategory: ").append(toIndentedString(trainCategory)).append("\n");
    sb.append("    trainType: ").append(toIndentedString(trainType)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    journeySections: ").append(toIndentedString(journeySections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

