/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.PassengerTerm;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Category code that is one step more detailed from its parent CategoryCode
 */
@JsonPropertyOrder({
  DetailedCategoryCode.JSON_PROPERTY_PASSENGER_TERM,
  DetailedCategoryCode.JSON_PROPERTY_DETAILED_CATEGORY_CODE,
  DetailedCategoryCode.JSON_PROPERTY_DETAILED_CATEGORY_NAME,
  DetailedCategoryCode.JSON_PROPERTY_VALID_FROM,
  DetailedCategoryCode.JSON_PROPERTY_VALID_TO,
  DetailedCategoryCode.JSON_PROPERTY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class DetailedCategoryCode {
  public static final String JSON_PROPERTY_PASSENGER_TERM = "passengerTerm";
  private PassengerTerm passengerTerm;

  public static final String JSON_PROPERTY_DETAILED_CATEGORY_CODE = "detailedCategoryCode";
  private String detailedCategoryCode;

  public static final String JSON_PROPERTY_DETAILED_CATEGORY_NAME = "detailedCategoryName";
  private String detailedCategoryName;

  public static final String JSON_PROPERTY_VALID_FROM = "validFrom";
  private LocalDate validFrom;

  public static final String JSON_PROPERTY_VALID_TO = "validTo";
  private LocalDate validTo;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public DetailedCategoryCode() {
  }

  public DetailedCategoryCode passengerTerm(PassengerTerm passengerTerm) {
    
    this.passengerTerm = passengerTerm;
    return this;
  }

   /**
   * Get passengerTerm
   * @return passengerTerm
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSENGER_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PassengerTerm getPassengerTerm() {
    return passengerTerm;
  }


  @JsonProperty(JSON_PROPERTY_PASSENGER_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassengerTerm(PassengerTerm passengerTerm) {
    this.passengerTerm = passengerTerm;
  }


  public DetailedCategoryCode detailedCategoryCode(String detailedCategoryCode) {
    
    this.detailedCategoryCode = detailedCategoryCode;
    return this;
  }

   /**
   * Get detailedCategoryCode
   * @return detailedCategoryCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDetailedCategoryCode() {
    return detailedCategoryCode;
  }


  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetailedCategoryCode(String detailedCategoryCode) {
    this.detailedCategoryCode = detailedCategoryCode;
  }


  public DetailedCategoryCode detailedCategoryName(String detailedCategoryName) {
    
    this.detailedCategoryName = detailedCategoryName;
    return this;
  }

   /**
   * Get detailedCategoryName
   * @return detailedCategoryName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDetailedCategoryName() {
    return detailedCategoryName;
  }


  @JsonProperty(JSON_PROPERTY_DETAILED_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetailedCategoryName(String detailedCategoryName) {
    this.detailedCategoryName = detailedCategoryName;
  }


  public DetailedCategoryCode validFrom(LocalDate validFrom) {
    
    this.validFrom = validFrom;
    return this;
  }

   /**
   * Start date when this category code is used
   * @return validFrom
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getValidFrom() {
    return validFrom;
  }


  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidFrom(LocalDate validFrom) {
    this.validFrom = validFrom;
  }


  public DetailedCategoryCode validTo(LocalDate validTo) {
    
    this.validTo = validTo;
    return this;
  }

   /**
   * End date when this code is used. Empty means category is used until further notice
   * @return validTo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getValidTo() {
    return validTo;
  }


  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidTo(LocalDate validTo) {
    this.validTo = validTo;
  }


  public DetailedCategoryCode id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedCategoryCode detailedCategoryCode = (DetailedCategoryCode) o;
    return Objects.equals(this.passengerTerm, detailedCategoryCode.passengerTerm) &&
        Objects.equals(this.detailedCategoryCode, detailedCategoryCode.detailedCategoryCode) &&
        Objects.equals(this.detailedCategoryName, detailedCategoryCode.detailedCategoryName) &&
        Objects.equals(this.validFrom, detailedCategoryCode.validFrom) &&
        Objects.equals(this.validTo, detailedCategoryCode.validTo) &&
        Objects.equals(this.id, detailedCategoryCode.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passengerTerm, detailedCategoryCode, detailedCategoryName, validFrom, validTo, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedCategoryCode {\n");
    sb.append("    passengerTerm: ").append(toIndentedString(passengerTerm)).append("\n");
    sb.append("    detailedCategoryCode: ").append(toIndentedString(detailedCategoryCode)).append("\n");
    sb.append("    detailedCategoryName: ").append(toIndentedString(detailedCategoryName)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

