/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Two consecutive elements in an identifier range
 */
@JsonPropertyOrder({
  ElementRange.JSON_PROPERTY_ELEMENT_ID1,
  ElementRange.JSON_PROPERTY_ELEMENT_ID2,
  ElementRange.JSON_PROPERTY_TRACK_KILOMETER_RANGE,
  ElementRange.JSON_PROPERTY_TRACK_IDS,
  ElementRange.JSON_PROPERTY_SPECIFIERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class ElementRange {
  public static final String JSON_PROPERTY_ELEMENT_ID1 = "elementId1";
  private String elementId1;

  public static final String JSON_PROPERTY_ELEMENT_ID2 = "elementId2";
  private String elementId2;

  public static final String JSON_PROPERTY_TRACK_KILOMETER_RANGE = "trackKilometerRange";
  private String trackKilometerRange;

  public static final String JSON_PROPERTY_TRACK_IDS = "trackIds";
  private List<String> trackIds = new ArrayList<>();

  public static final String JSON_PROPERTY_SPECIFIERS = "specifiers";
  private List<String> specifiers;

  public ElementRange() {
  }

  public ElementRange elementId1(String elementId1) {
    
    this.elementId1 = elementId1;
    return this;
  }

   /**
   * Identifier of element 1
   * @return elementId1
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ELEMENT_ID1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getElementId1() {
    return elementId1;
  }


  @JsonProperty(JSON_PROPERTY_ELEMENT_ID1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setElementId1(String elementId1) {
    this.elementId1 = elementId1;
  }


  public ElementRange elementId2(String elementId2) {
    
    this.elementId2 = elementId2;
    return this;
  }

   /**
   * Identifier of element 2
   * @return elementId2
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ELEMENT_ID2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getElementId2() {
    return elementId2;
  }


  @JsonProperty(JSON_PROPERTY_ELEMENT_ID2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setElementId2(String elementId2) {
    this.elementId2 = elementId2;
  }


  public ElementRange trackKilometerRange(String trackKilometerRange) {
    
    this.trackKilometerRange = trackKilometerRange;
    return this;
  }

   /**
   * Track kilometer range, required if notification type is traffic restriction, e.g. (006) 754+0273 &gt; 764+0771
   * @return trackKilometerRange
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_KILOMETER_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackKilometerRange() {
    return trackKilometerRange;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_KILOMETER_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackKilometerRange(String trackKilometerRange) {
    this.trackKilometerRange = trackKilometerRange;
  }


  public ElementRange trackIds(List<String> trackIds) {
    
    this.trackIds = trackIds;
    return this;
  }

  public ElementRange addTrackIdsItem(String trackIdsItem) {
    if (this.trackIds == null) {
      this.trackIds = new ArrayList<>();
    }
    this.trackIds.add(trackIdsItem);
    return this;
  }

   /**
   * Track identifiers
   * @return trackIds
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRACK_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getTrackIds() {
    return trackIds;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrackIds(List<String> trackIds) {
    this.trackIds = trackIds;
  }


  public ElementRange specifiers(List<String> specifiers) {
    
    this.specifiers = specifiers;
    return this;
  }

  public ElementRange addSpecifiersItem(String specifiersItem) {
    if (this.specifiers == null) {
      this.specifiers = new ArrayList<>();
    }
    this.specifiers.add(specifiersItem);
    return this;
  }

   /**
   * Specify a more detailed work area (track element)
   * @return specifiers
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPECIFIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSpecifiers() {
    return specifiers;
  }


  @JsonProperty(JSON_PROPERTY_SPECIFIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecifiers(List<String> specifiers) {
    this.specifiers = specifiers;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElementRange elementRange = (ElementRange) o;
    return Objects.equals(this.elementId1, elementRange.elementId1) &&
        Objects.equals(this.elementId2, elementRange.elementId2) &&
        Objects.equals(this.trackKilometerRange, elementRange.trackKilometerRange) &&
        Objects.equals(this.trackIds, elementRange.trackIds) &&
        Objects.equals(this.specifiers, elementRange.specifiers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(elementId1, elementId2, trackKilometerRange, trackIds, specifiers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ElementRange {\n");
    sb.append("    elementId1: ").append(toIndentedString(elementId1)).append("\n");
    sb.append("    elementId2: ").append(toIndentedString(elementId2)).append("\n");
    sb.append("    trackKilometerRange: ").append(toIndentedString(trackKilometerRange)).append("\n");
    sb.append("    trackIds: ").append(toIndentedString(trackIds)).append("\n");
    sb.append("    specifiers: ").append(toIndentedString(specifiers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

