/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import fi.digitraffic.traingraph.model.ElementRange;
import fi.digitraffic.traingraph.model.SpeedLimit;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Place of work: between two track elements or a single track element
 */
@JsonPropertyOrder({
  IdentifierRange.JSON_PROPERTY_NOTIFICATION_ID,
  IdentifierRange.JSON_PROPERTY_ELEMENT_ID,
  IdentifierRange.JSON_PROPERTY_ELEMENT_PAIR_ID1,
  IdentifierRange.JSON_PROPERTY_ELEMENT_PAIR_ID2,
  IdentifierRange.JSON_PROPERTY_SPEED_LIMIT,
  IdentifierRange.JSON_PROPERTY_ELEMENT_RANGES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class IdentifierRange {
  public static final String JSON_PROPERTY_NOTIFICATION_ID = "notificationId";
  private String notificationId;

  public static final String JSON_PROPERTY_ELEMENT_ID = "elementId";
  private String elementId;

  public static final String JSON_PROPERTY_ELEMENT_PAIR_ID1 = "elementPairId1";
  private String elementPairId1;

  public static final String JSON_PROPERTY_ELEMENT_PAIR_ID2 = "elementPairId2";
  private String elementPairId2;

  public static final String JSON_PROPERTY_SPEED_LIMIT = "speedLimit";
  private SpeedLimit speedLimit;

  public static final String JSON_PROPERTY_ELEMENT_RANGES = "elementRanges";
  private Set<ElementRange> elementRanges;

  public IdentifierRange() {
  }

  public IdentifierRange notificationId(String notificationId) {
    
    this.notificationId = notificationId;
    return this;
  }

   /**
   * Notification identifier
   * @return notificationId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NOTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNotificationId() {
    return notificationId;
  }


  @JsonProperty(JSON_PROPERTY_NOTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotificationId(String notificationId) {
    this.notificationId = notificationId;
  }


  public IdentifierRange elementId(String elementId) {
    
    this.elementId = elementId;
    return this;
  }

   /**
   * Identifier of element, required if element pair or ranges are not present
   * @return elementId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getElementId() {
    return elementId;
  }


  @JsonProperty(JSON_PROPERTY_ELEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElementId(String elementId) {
    this.elementId = elementId;
  }


  public IdentifierRange elementPairId1(String elementPairId1) {
    
    this.elementPairId1 = elementPairId1;
    return this;
  }

   /**
   * Identifier of element 1 in element pair, required if element or ranges are not present
   * @return elementPairId1
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELEMENT_PAIR_ID1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getElementPairId1() {
    return elementPairId1;
  }


  @JsonProperty(JSON_PROPERTY_ELEMENT_PAIR_ID1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElementPairId1(String elementPairId1) {
    this.elementPairId1 = elementPairId1;
  }


  public IdentifierRange elementPairId2(String elementPairId2) {
    
    this.elementPairId2 = elementPairId2;
    return this;
  }

   /**
   * Identifier of element 2 in element pair, required if element or ranges are not present
   * @return elementPairId2
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELEMENT_PAIR_ID2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getElementPairId2() {
    return elementPairId2;
  }


  @JsonProperty(JSON_PROPERTY_ELEMENT_PAIR_ID2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElementPairId2(String elementPairId2) {
    this.elementPairId2 = elementPairId2;
  }


  public IdentifierRange speedLimit(SpeedLimit speedLimit) {
    
    this.speedLimit = speedLimit;
    return this;
  }

   /**
   * Get speedLimit
   * @return speedLimit
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPEED_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SpeedLimit getSpeedLimit() {
    return speedLimit;
  }


  @JsonProperty(JSON_PROPERTY_SPEED_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpeedLimit(SpeedLimit speedLimit) {
    this.speedLimit = speedLimit;
  }


  public IdentifierRange elementRanges(Set<ElementRange> elementRanges) {
    
    this.elementRanges = elementRanges;
    return this;
  }

  public IdentifierRange addElementRangesItem(ElementRange elementRangesItem) {
    if (this.elementRanges == null) {
      this.elementRanges = new LinkedHashSet<>();
    }
    this.elementRanges.add(elementRangesItem);
    return this;
  }

   /**
   * Element ranges, required if element or element pair is not present
   * @return elementRanges
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELEMENT_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<ElementRange> getElementRanges() {
    return elementRanges;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_ELEMENT_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElementRanges(Set<ElementRange> elementRanges) {
    this.elementRanges = elementRanges;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentifierRange identifierRange = (IdentifierRange) o;
    return Objects.equals(this.notificationId, identifierRange.notificationId) &&
        Objects.equals(this.elementId, identifierRange.elementId) &&
        Objects.equals(this.elementPairId1, identifierRange.elementPairId1) &&
        Objects.equals(this.elementPairId2, identifierRange.elementPairId2) &&
        Objects.equals(this.speedLimit, identifierRange.speedLimit) &&
        Objects.equals(this.elementRanges, identifierRange.elementRanges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notificationId, elementId, elementPairId1, elementPairId2, speedLimit, elementRanges);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentifierRange {\n");
    sb.append("    notificationId: ").append(toIndentedString(notificationId)).append("\n");
    sb.append("    elementId: ").append(toIndentedString(elementId)).append("\n");
    sb.append("    elementPairId1: ").append(toIndentedString(elementPairId1)).append("\n");
    sb.append("    elementPairId2: ").append(toIndentedString(elementPairId2)).append("\n");
    sb.append("    speedLimit: ").append(toIndentedString(speedLimit)).append("\n");
    sb.append("    elementRanges: ").append(toIndentedString(elementRanges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

