/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import fi.digitraffic.traingraph.model.CompositionTimeTableRow;
import fi.digitraffic.traingraph.model.Locomotive;
import fi.digitraffic.traingraph.model.Wagon;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Describes a leg where train&#39;s composition is in effect
 */
@JsonPropertyOrder({
  JourneySection.JSON_PROPERTY_BEGIN_TIME_TABLE_ROW,
  JourneySection.JSON_PROPERTY_END_TIME_TABLE_ROW,
  JourneySection.JSON_PROPERTY_LOCOMOTIVES,
  JourneySection.JSON_PROPERTY_WAGONS,
  JourneySection.JSON_PROPERTY_TOTAL_LENGTH,
  JourneySection.JSON_PROPERTY_MAXIMUM_SPEED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class JourneySection {
  public static final String JSON_PROPERTY_BEGIN_TIME_TABLE_ROW = "beginTimeTableRow";
  private CompositionTimeTableRow beginTimeTableRow;

  public static final String JSON_PROPERTY_END_TIME_TABLE_ROW = "endTimeTableRow";
  private CompositionTimeTableRow endTimeTableRow;

  public static final String JSON_PROPERTY_LOCOMOTIVES = "locomotives";
  private Set<Locomotive> locomotives;

  public static final String JSON_PROPERTY_WAGONS = "wagons";
  private Set<Wagon> wagons;

  public static final String JSON_PROPERTY_TOTAL_LENGTH = "totalLength";
  private Integer totalLength;

  public static final String JSON_PROPERTY_MAXIMUM_SPEED = "maximumSpeed";
  private Integer maximumSpeed;

  public JourneySection() {
  }

  public JourneySection beginTimeTableRow(CompositionTimeTableRow beginTimeTableRow) {
    
    this.beginTimeTableRow = beginTimeTableRow;
    return this;
  }

   /**
   * Get beginTimeTableRow
   * @return beginTimeTableRow
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BEGIN_TIME_TABLE_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CompositionTimeTableRow getBeginTimeTableRow() {
    return beginTimeTableRow;
  }


  @JsonProperty(JSON_PROPERTY_BEGIN_TIME_TABLE_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeginTimeTableRow(CompositionTimeTableRow beginTimeTableRow) {
    this.beginTimeTableRow = beginTimeTableRow;
  }


  public JourneySection endTimeTableRow(CompositionTimeTableRow endTimeTableRow) {
    
    this.endTimeTableRow = endTimeTableRow;
    return this;
  }

   /**
   * Get endTimeTableRow
   * @return endTimeTableRow
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_TIME_TABLE_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CompositionTimeTableRow getEndTimeTableRow() {
    return endTimeTableRow;
  }


  @JsonProperty(JSON_PROPERTY_END_TIME_TABLE_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTimeTableRow(CompositionTimeTableRow endTimeTableRow) {
    this.endTimeTableRow = endTimeTableRow;
  }


  public JourneySection locomotives(Set<Locomotive> locomotives) {
    
    this.locomotives = locomotives;
    return this;
  }

  public JourneySection addLocomotivesItem(Locomotive locomotivesItem) {
    if (this.locomotives == null) {
      this.locomotives = new LinkedHashSet<>();
    }
    this.locomotives.add(locomotivesItem);
    return this;
  }

   /**
   * List of locomotives used on this leg
   * @return locomotives
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCOMOTIVES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<Locomotive> getLocomotives() {
    return locomotives;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_LOCOMOTIVES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocomotives(Set<Locomotive> locomotives) {
    this.locomotives = locomotives;
  }


  public JourneySection wagons(Set<Wagon> wagons) {
    
    this.wagons = wagons;
    return this;
  }

  public JourneySection addWagonsItem(Wagon wagonsItem) {
    if (this.wagons == null) {
      this.wagons = new LinkedHashSet<>();
    }
    this.wagons.add(wagonsItem);
    return this;
  }

   /**
   * List of wagons used on this leg
   * @return wagons
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WAGONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<Wagon> getWagons() {
    return wagons;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_WAGONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWagons(Set<Wagon> wagons) {
    this.wagons = wagons;
  }


  public JourneySection totalLength(Integer totalLength) {
    
    this.totalLength = totalLength;
    return this;
  }

   /**
   * Total length of the train with an accuracy of 1 m
   * @return totalLength
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalLength() {
    return totalLength;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalLength(Integer totalLength) {
    this.totalLength = totalLength;
  }


  public JourneySection maximumSpeed(Integer maximumSpeed) {
    
    this.maximumSpeed = maximumSpeed;
    return this;
  }

   /**
   * Maximum with an accuracy of 1 km/h
   * @return maximumSpeed
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAXIMUM_SPEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaximumSpeed() {
    return maximumSpeed;
  }


  @JsonProperty(JSON_PROPERTY_MAXIMUM_SPEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaximumSpeed(Integer maximumSpeed) {
    this.maximumSpeed = maximumSpeed;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneySection journeySection = (JourneySection) o;
    return Objects.equals(this.beginTimeTableRow, journeySection.beginTimeTableRow) &&
        Objects.equals(this.endTimeTableRow, journeySection.endTimeTableRow) &&
        Objects.equals(this.locomotives, journeySection.locomotives) &&
        Objects.equals(this.wagons, journeySection.wagons) &&
        Objects.equals(this.totalLength, journeySection.totalLength) &&
        Objects.equals(this.maximumSpeed, journeySection.maximumSpeed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beginTimeTableRow, endTimeTableRow, locomotives, wagons, totalLength, maximumSpeed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneySection {\n");
    sb.append("    beginTimeTableRow: ").append(toIndentedString(beginTimeTableRow)).append("\n");
    sb.append("    endTimeTableRow: ").append(toIndentedString(endTimeTableRow)).append("\n");
    sb.append("    locomotives: ").append(toIndentedString(locomotives)).append("\n");
    sb.append("    wagons: ").append(toIndentedString(wagons)).append("\n");
    sb.append("    totalLength: ").append(toIndentedString(totalLength)).append("\n");
    sb.append("    maximumSpeed: ").append(toIndentedString(maximumSpeed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

