/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * List of locomotives used on this leg
 */
@JsonPropertyOrder({
  Locomotive.JSON_PROPERTY_LOCATION,
  Locomotive.JSON_PROPERTY_LOCOMOTIVE_TYPE,
  Locomotive.JSON_PROPERTY_POWER_TYPE,
  Locomotive.JSON_PROPERTY_VEHICLE_NUMBER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class Locomotive {
  public static final String JSON_PROPERTY_LOCATION = "location";
  private Integer location;

  public static final String JSON_PROPERTY_LOCOMOTIVE_TYPE = "locomotiveType";
  private String locomotiveType;

  public static final String JSON_PROPERTY_POWER_TYPE = "powerType";
  private String powerType;

  public static final String JSON_PROPERTY_VEHICLE_NUMBER = "vehicleNumber";
  private String vehicleNumber;

  public Locomotive() {
  }

  public Locomotive location(Integer location) {
    
    this.location = location;
    return this;
  }

   /**
   * Location of the locomotive in the train. 1&#x3D;start of the train
   * @return location
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(Integer location) {
    this.location = location;
  }


  public Locomotive locomotiveType(String locomotiveType) {
    
    this.locomotiveType = locomotiveType;
    return this;
  }

   /**
   * Get locomotiveType
   * @return locomotiveType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCOMOTIVE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocomotiveType() {
    return locomotiveType;
  }


  @JsonProperty(JSON_PROPERTY_LOCOMOTIVE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocomotiveType(String locomotiveType) {
    this.locomotiveType = locomotiveType;
  }


  public Locomotive powerType(String powerType) {
    
    this.powerType = powerType;
    return this;
  }

   /**
   * Get powerType
   * @return powerType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POWER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPowerType() {
    return powerType;
  }


  @JsonProperty(JSON_PROPERTY_POWER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPowerType(String powerType) {
    this.powerType = powerType;
  }


  public Locomotive vehicleNumber(String vehicleNumber) {
    
    this.vehicleNumber = vehicleNumber;
    return this;
  }

   /**
   * Get vehicleNumber
   * @return vehicleNumber
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VEHICLE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVehicleNumber() {
    return vehicleNumber;
  }


  @JsonProperty(JSON_PROPERTY_VEHICLE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVehicleNumber(String vehicleNumber) {
    this.vehicleNumber = vehicleNumber;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Locomotive locomotive = (Locomotive) o;
    return Objects.equals(this.location, locomotive.location) &&
        Objects.equals(this.locomotiveType, locomotive.locomotiveType) &&
        Objects.equals(this.powerType, locomotive.powerType) &&
        Objects.equals(this.vehicleNumber, locomotive.vehicleNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(location, locomotiveType, powerType, vehicleNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Locomotive {\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    locomotiveType: ").append(toIndentedString(locomotiveType)).append("\n");
    sb.append("    powerType: ").append(toIndentedString(powerType)).append("\n");
    sb.append("    vehicleNumber: ").append(toIndentedString(vehicleNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

