/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import fi.digitraffic.traingraph.model.OperatorTrainNumber;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Operator
 */
@JsonPropertyOrder({
  Operator.JSON_PROPERTY_ID,
  Operator.JSON_PROPERTY_OPERATOR_NAME,
  Operator.JSON_PROPERTY_OPERATOR_SHORT_CODE,
  Operator.JSON_PROPERTY_OPERATOR_U_I_C_CODE,
  Operator.JSON_PROPERTY_TRAIN_NUMBERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class Operator {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_OPERATOR_NAME = "operatorName";
  private String operatorName;

  public static final String JSON_PROPERTY_OPERATOR_SHORT_CODE = "operatorShortCode";
  private String operatorShortCode;

  public static final String JSON_PROPERTY_OPERATOR_U_I_C_CODE = "operatorUICCode";
  private Integer operatorUICCode;

  public static final String JSON_PROPERTY_TRAIN_NUMBERS = "trainNumbers";
  private Set<OperatorTrainNumber> trainNumbers;

  public Operator() {
  }

  public Operator id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public Operator operatorName(String operatorName) {
    
    this.operatorName = operatorName;
    return this;
  }

   /**
   * Get operatorName
   * @return operatorName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperatorName() {
    return operatorName;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatorName(String operatorName) {
    this.operatorName = operatorName;
  }


  public Operator operatorShortCode(String operatorShortCode) {
    
    this.operatorShortCode = operatorShortCode;
    return this;
  }

   /**
   * Get operatorShortCode
   * @return operatorShortCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperatorShortCode() {
    return operatorShortCode;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatorShortCode(String operatorShortCode) {
    this.operatorShortCode = operatorShortCode;
  }


  public Operator operatorUICCode(Integer operatorUICCode) {
    
    this.operatorUICCode = operatorUICCode;
    return this;
  }

   /**
   * Get operatorUICCode
   * @return operatorUICCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOperatorUICCode() {
    return operatorUICCode;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatorUICCode(Integer operatorUICCode) {
    this.operatorUICCode = operatorUICCode;
  }


  public Operator trainNumbers(Set<OperatorTrainNumber> trainNumbers) {
    
    this.trainNumbers = trainNumbers;
    return this;
  }

  public Operator addTrainNumbersItem(OperatorTrainNumber trainNumbersItem) {
    if (this.trainNumbers == null) {
      this.trainNumbers = new LinkedHashSet<>();
    }
    this.trainNumbers.add(trainNumbersItem);
    return this;
  }

   /**
   * Get trainNumbers
   * @return trainNumbers
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<OperatorTrainNumber> getTrainNumbers() {
    return trainNumbers;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainNumbers(Set<OperatorTrainNumber> trainNumbers) {
    this.trainNumbers = trainNumbers;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Operator operator = (Operator) o;
    return Objects.equals(this.id, operator.id) &&
        Objects.equals(this.operatorName, operator.operatorName) &&
        Objects.equals(this.operatorShortCode, operator.operatorShortCode) &&
        Objects.equals(this.operatorUICCode, operator.operatorUICCode) &&
        Objects.equals(this.trainNumbers, operator.trainNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, operatorName, operatorShortCode, operatorUICCode, trainNumbers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Operator {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    operatorName: ").append(toIndentedString(operatorName)).append("\n");
    sb.append("    operatorShortCode: ").append(toIndentedString(operatorShortCode)).append("\n");
    sb.append("    operatorUICCode: ").append(toIndentedString(operatorUICCode)).append("\n");
    sb.append("    trainNumbers: ").append(toIndentedString(trainNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

