/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PassengerInformationVideoDeliveryRules
 */
@JsonPropertyOrder({
  PassengerInformationVideoDeliveryRules.JSON_PROPERTY_START_DATE_TIME,
  PassengerInformationVideoDeliveryRules.JSON_PROPERTY_WEEK_DAYS,
  PassengerInformationVideoDeliveryRules.JSON_PROPERTY_DELIVERY_TYPE,
  PassengerInformationVideoDeliveryRules.JSON_PROPERTY_START_TIME,
  PassengerInformationVideoDeliveryRules.JSON_PROPERTY_END_TIME,
  PassengerInformationVideoDeliveryRules.JSON_PROPERTY_END_DATE_TIME
})
@JsonTypeName("PassengerInformationVideo_deliveryRules")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class PassengerInformationVideoDeliveryRules {
  public static final String JSON_PROPERTY_START_DATE_TIME = "startDateTime";
  private String startDateTime;

  /**
   * Gets or Sets weekDays
   */
  public enum WeekDaysEnum {
    MONDAY("MONDAY"),
    
    TUESDAY("TUESDAY"),
    
    WEDNESDAY("WEDNESDAY"),
    
    THURSDAY("THURSDAY"),
    
    FRIDAY("FRIDAY"),
    
    SATURDAY("SATURDAY"),
    
    SUNDAY("SUNDAY");

    private String value;

    WeekDaysEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WeekDaysEnum fromValue(String value) {
      for (WeekDaysEnum b : WeekDaysEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_WEEK_DAYS = "weekDays";
  private List<WeekDaysEnum> weekDays;

  /**
   * CONTINUOS_VISUALIZATION: the message is delivered from _startDateTime_ (at _startTime_ if exists) to _endDateTime_ (at _endTime_ if exists)   WHEN: the message is delivered  from  _startDateTime_ to _endDateTime_ only in the time interval between _startTime_ and _endTime_ for each day in _weekDays_
   */
  public enum DeliveryTypeEnum {
    WHEN("WHEN"),
    
    CONTINUOS_VISUALIZATION("CONTINUOS_VISUALIZATION");

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_TYPE = "deliveryType";
  private DeliveryTypeEnum deliveryType;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  private String startTime;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  private String endTime;

  public static final String JSON_PROPERTY_END_DATE_TIME = "endDateTime";
  private String endDateTime;

  public PassengerInformationVideoDeliveryRules() {
  }

  public PassengerInformationVideoDeliveryRules startDateTime(String startDateTime) {
    
    this.startDateTime = startDateTime;
    return this;
  }

   /**
   * Video delivery start date
   * @return startDateTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartDateTime() {
    return startDateTime;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDateTime(String startDateTime) {
    this.startDateTime = startDateTime;
  }


  public PassengerInformationVideoDeliveryRules weekDays(List<WeekDaysEnum> weekDays) {
    
    this.weekDays = weekDays;
    return this;
  }

  public PassengerInformationVideoDeliveryRules addWeekDaysItem(WeekDaysEnum weekDaysItem) {
    if (this.weekDays == null) {
      this.weekDays = new ArrayList<>();
    }
    this.weekDays.add(weekDaysItem);
    return this;
  }

   /**
   * Days of week on which video is delivered
   * @return weekDays
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEEK_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<WeekDaysEnum> getWeekDays() {
    return weekDays;
  }


  @JsonProperty(JSON_PROPERTY_WEEK_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeekDays(List<WeekDaysEnum> weekDays) {
    this.weekDays = weekDays;
  }


  public PassengerInformationVideoDeliveryRules deliveryType(DeliveryTypeEnum deliveryType) {
    
    this.deliveryType = deliveryType;
    return this;
  }

   /**
   * CONTINUOS_VISUALIZATION: the message is delivered from _startDateTime_ (at _startTime_ if exists) to _endDateTime_ (at _endTime_ if exists)   WHEN: the message is delivered  from  _startDateTime_ to _endDateTime_ only in the time interval between _startTime_ and _endTime_ for each day in _weekDays_
   * @return deliveryType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryType(DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public PassengerInformationVideoDeliveryRules startTime(String startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * Video delivery start time
   * @return startTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }


  public PassengerInformationVideoDeliveryRules endTime(String endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * Video delivery end time
   * @return endTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndTime() {
    return endTime;
  }


  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  public PassengerInformationVideoDeliveryRules endDateTime(String endDateTime) {
    
    this.endDateTime = endDateTime;
    return this;
  }

   /**
   * Video delivery end date
   * @return endDateTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndDateTime() {
    return endDateTime;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDateTime(String endDateTime) {
    this.endDateTime = endDateTime;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PassengerInformationVideoDeliveryRules passengerInformationVideoDeliveryRules = (PassengerInformationVideoDeliveryRules) o;
    return Objects.equals(this.startDateTime, passengerInformationVideoDeliveryRules.startDateTime) &&
        Objects.equals(this.weekDays, passengerInformationVideoDeliveryRules.weekDays) &&
        Objects.equals(this.deliveryType, passengerInformationVideoDeliveryRules.deliveryType) &&
        Objects.equals(this.startTime, passengerInformationVideoDeliveryRules.startTime) &&
        Objects.equals(this.endTime, passengerInformationVideoDeliveryRules.endTime) &&
        Objects.equals(this.endDateTime, passengerInformationVideoDeliveryRules.endDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDateTime, weekDays, deliveryType, startTime, endTime, endDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PassengerInformationVideoDeliveryRules {\n");
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    weekDays: ").append(toIndentedString(weekDays)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    endDateTime: ").append(toIndentedString(endDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

