/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.PassengerInformationAudio;
import fi.digitraffic.traingraph.model.PassengerInformationVideo;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PassengerInformation message schema
 */
@JsonPropertyOrder({
  PassengerInformationMessage.JSON_PROPERTY_TRAIN_DEPARTURE_DATE,
  PassengerInformationMessage.JSON_PROPERTY_END_VALIDITY,
  PassengerInformationMessage.JSON_PROPERTY_START_VALIDITY,
  PassengerInformationMessage.JSON_PROPERTY_ID,
  PassengerInformationMessage.JSON_PROPERTY_STATIONS,
  PassengerInformationMessage.JSON_PROPERTY_TRAIN_NUMBER,
  PassengerInformationMessage.JSON_PROPERTY_AUDIO,
  PassengerInformationMessage.JSON_PROPERTY_VIDEO,
  PassengerInformationMessage.JSON_PROPERTY_VERSION,
  PassengerInformationMessage.JSON_PROPERTY_CREATION_DATE_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class PassengerInformationMessage {
  public static final String JSON_PROPERTY_TRAIN_DEPARTURE_DATE = "trainDepartureDate";
  private String trainDepartureDate;

  public static final String JSON_PROPERTY_END_VALIDITY = "endValidity";
  private String endValidity;

  public static final String JSON_PROPERTY_START_VALIDITY = "startValidity";
  private String startValidity;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_STATIONS = "stations";
  private List<String> stations;

  public static final String JSON_PROPERTY_TRAIN_NUMBER = "trainNumber";
  private String trainNumber;

  public static final String JSON_PROPERTY_AUDIO = "audio";
  private PassengerInformationAudio audio;

  public static final String JSON_PROPERTY_VIDEO = "video";
  private PassengerInformationVideo video;

  public static final String JSON_PROPERTY_VERSION = "version";
  private BigDecimal version;

  public static final String JSON_PROPERTY_CREATION_DATE_TIME = "creationDateTime";
  private String creationDateTime;

  public PassengerInformationMessage() {
  }

  public PassengerInformationMessage trainDepartureDate(String trainDepartureDate) {
    
    this.trainDepartureDate = trainDepartureDate;
    return this;
  }

   /**
   * Date of departure as a local date for train to which message relates
   * @return trainDepartureDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrainDepartureDate() {
    return trainDepartureDate;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainDepartureDate(String trainDepartureDate) {
    this.trainDepartureDate = trainDepartureDate;
  }


  public PassengerInformationMessage endValidity(String endValidity) {
    
    this.endValidity = endValidity;
    return this;
  }

   /**
   * Message validity end date and time
   * @return endValidity
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_END_VALIDITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEndValidity() {
    return endValidity;
  }


  @JsonProperty(JSON_PROPERTY_END_VALIDITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndValidity(String endValidity) {
    this.endValidity = endValidity;
  }


  public PassengerInformationMessage startValidity(String startValidity) {
    
    this.startValidity = startValidity;
    return this;
  }

   /**
   * Message validity start date and time
   * @return startValidity
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_START_VALIDITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStartValidity() {
    return startValidity;
  }


  @JsonProperty(JSON_PROPERTY_START_VALIDITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartValidity(String startValidity) {
    this.startValidity = startValidity;
  }


  public PassengerInformationMessage id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public PassengerInformationMessage stations(List<String> stations) {
    
    this.stations = stations;
    return this;
  }

  public PassengerInformationMessage addStationsItem(String stationsItem) {
    if (this.stations == null) {
      this.stations = new ArrayList<>();
    }
    this.stations.add(stationsItem);
    return this;
  }

   /**
   * List of stations where message is delivered
   * @return stations
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getStations() {
    return stations;
  }


  @JsonProperty(JSON_PROPERTY_STATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStations(List<String> stations) {
    this.stations = stations;
  }


  public PassengerInformationMessage trainNumber(String trainNumber) {
    
    this.trainNumber = trainNumber;
    return this;
  }

   /**
   * Number of train to which message relates
   * @return trainNumber
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrainNumber() {
    return trainNumber;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainNumber(String trainNumber) {
    this.trainNumber = trainNumber;
  }


  public PassengerInformationMessage audio(PassengerInformationAudio audio) {
    
    this.audio = audio;
    return this;
  }

   /**
   * Get audio
   * @return audio
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUDIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PassengerInformationAudio getAudio() {
    return audio;
  }


  @JsonProperty(JSON_PROPERTY_AUDIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAudio(PassengerInformationAudio audio) {
    this.audio = audio;
  }


  public PassengerInformationMessage video(PassengerInformationVideo video) {
    
    this.video = video;
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VIDEO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PassengerInformationVideo getVideo() {
    return video;
  }


  @JsonProperty(JSON_PROPERTY_VIDEO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideo(PassengerInformationVideo video) {
    this.video = video;
  }


  public PassengerInformationMessage version(BigDecimal version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(BigDecimal version) {
    this.version = version;
  }


  public PassengerInformationMessage creationDateTime(String creationDateTime) {
    
    this.creationDateTime = creationDateTime;
    return this;
  }

   /**
   * Date and time when message version was created
   * @return creationDateTime
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATION_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCreationDateTime() {
    return creationDateTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreationDateTime(String creationDateTime) {
    this.creationDateTime = creationDateTime;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PassengerInformationMessage passengerInformationMessage = (PassengerInformationMessage) o;
    return Objects.equals(this.trainDepartureDate, passengerInformationMessage.trainDepartureDate) &&
        Objects.equals(this.endValidity, passengerInformationMessage.endValidity) &&
        Objects.equals(this.startValidity, passengerInformationMessage.startValidity) &&
        Objects.equals(this.id, passengerInformationMessage.id) &&
        Objects.equals(this.stations, passengerInformationMessage.stations) &&
        Objects.equals(this.trainNumber, passengerInformationMessage.trainNumber) &&
        Objects.equals(this.audio, passengerInformationMessage.audio) &&
        Objects.equals(this.video, passengerInformationMessage.video) &&
        Objects.equals(this.version, passengerInformationMessage.version) &&
        Objects.equals(this.creationDateTime, passengerInformationMessage.creationDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trainDepartureDate, endValidity, startValidity, id, stations, trainNumber, audio, video, version, creationDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PassengerInformationMessage {\n");
    sb.append("    trainDepartureDate: ").append(toIndentedString(trainDepartureDate)).append("\n");
    sb.append("    endValidity: ").append(toIndentedString(endValidity)).append("\n");
    sb.append("    startValidity: ").append(toIndentedString(startValidity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    stations: ").append(toIndentedString(stations)).append("\n");
    sb.append("    trainNumber: ").append(toIndentedString(trainNumber)).append("\n");
    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    creationDateTime: ").append(toIndentedString(creationDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

