/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.PassengerInformationTextContent;
import fi.digitraffic.traingraph.model.PassengerInformationVideoDeliveryRules;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PassengerInformation message video content schema
 */
@JsonPropertyOrder({
  PassengerInformationVideo.JSON_PROPERTY_TEXT,
  PassengerInformationVideo.JSON_PROPERTY_DELIVERY_RULES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class PassengerInformationVideo {
  public static final String JSON_PROPERTY_TEXT = "text";
  private PassengerInformationTextContent text;

  public static final String JSON_PROPERTY_DELIVERY_RULES = "deliveryRules";
  private PassengerInformationVideoDeliveryRules deliveryRules;

  public PassengerInformationVideo() {
  }

  public PassengerInformationVideo text(PassengerInformationTextContent text) {
    
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PassengerInformationTextContent getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(PassengerInformationTextContent text) {
    this.text = text;
  }


  public PassengerInformationVideo deliveryRules(PassengerInformationVideoDeliveryRules deliveryRules) {
    
    this.deliveryRules = deliveryRules;
    return this;
  }

   /**
   * Get deliveryRules
   * @return deliveryRules
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PassengerInformationVideoDeliveryRules getDeliveryRules() {
    return deliveryRules;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryRules(PassengerInformationVideoDeliveryRules deliveryRules) {
    this.deliveryRules = deliveryRules;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PassengerInformationVideo passengerInformationVideo = (PassengerInformationVideo) o;
    return Objects.equals(this.text, passengerInformationVideo.text) &&
        Objects.equals(this.deliveryRules, passengerInformationVideo.deliveryRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, deliveryRules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PassengerInformationVideo {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    deliveryRules: ").append(toIndentedString(deliveryRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

