/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PassengerTerm
 */
@JsonPropertyOrder({
  PassengerTerm.JSON_PROPERTY_FI,
  PassengerTerm.JSON_PROPERTY_EN,
  PassengerTerm.JSON_PROPERTY_SV
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class PassengerTerm {
  public static final String JSON_PROPERTY_FI = "fi";
  private String fi;

  public static final String JSON_PROPERTY_EN = "en";
  private String en;

  public static final String JSON_PROPERTY_SV = "sv";
  private String sv;

  public PassengerTerm() {
  }

  public PassengerTerm fi(String fi) {
    
    this.fi = fi;
    return this;
  }

   /**
   * Finnish passenger friendly term for the code
   * @return fi
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFi() {
    return fi;
  }


  @JsonProperty(JSON_PROPERTY_FI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFi(String fi) {
    this.fi = fi;
  }


  public PassengerTerm en(String en) {
    
    this.en = en;
    return this;
  }

   /**
   * English passenger friendly term for the code
   * @return en
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEn() {
    return en;
  }


  @JsonProperty(JSON_PROPERTY_EN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEn(String en) {
    this.en = en;
  }


  public PassengerTerm sv(String sv) {
    
    this.sv = sv;
    return this;
  }

   /**
   * Swedish passenger friendly term for the code
   * @return sv
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSv() {
    return sv;
  }


  @JsonProperty(JSON_PROPERTY_SV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSv(String sv) {
    this.sv = sv;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PassengerTerm passengerTerm = (PassengerTerm) o;
    return Objects.equals(this.fi, passengerTerm.fi) &&
        Objects.equals(this.en, passengerTerm.en) &&
        Objects.equals(this.sv, passengerTerm.sv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fi, en, sv);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PassengerTerm {\n");
    sb.append("    fi: ").append(toIndentedString(fi)).append("\n");
    sb.append("    en: ").append(toIndentedString(en)).append("\n");
    sb.append("    sv: ").append(toIndentedString(sv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

