/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PassengerInformationAudioDeliveryRules
 */
@JsonPropertyOrder({
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_START_DATE_TIME,
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_WEEK_DAYS,
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_DELIVERY_TYPE,
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_START_TIME,
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_DELIVERY_AT,
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_REPEAT_EVERY,
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_END_TIME,
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_EVENT_TYPE,
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_END_DATE_TIME,
  PassengerInformationAudioDeliveryRules.JSON_PROPERTY_REPETITIONS
})
@JsonTypeName("PassengerInformationAudio_deliveryRules")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class PassengerInformationAudioDeliveryRules {
  public static final String JSON_PROPERTY_START_DATE_TIME = "startDateTime";
  private String startDateTime;

  /**
   * Gets or Sets weekDays
   */
  public enum WeekDaysEnum {
    MONDAY("MONDAY"),
    
    TUESDAY("TUESDAY"),
    
    WEDNESDAY("WEDNESDAY"),
    
    THURSDAY("THURSDAY"),
    
    FRIDAY("FRIDAY"),
    
    SATURDAY("SATURDAY"),
    
    SUNDAY("SUNDAY");

    private String value;

    WeekDaysEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WeekDaysEnum fromValue(String value) {
      for (WeekDaysEnum b : WeekDaysEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_WEEK_DAYS = "weekDays";
  private List<WeekDaysEnum> weekDays;

  /**
   * NOW: the message is delivered at the time of insertion   DELIVERY_AT: the message is delivered on the date-time _deliveryAt_   REPEAT_EVERY: the message is delivered from _startDateTime_ at _startTime_ to _endDateTime_ at _endTime_ evaluating the repetition conditions and _weekDays_ conditions   ON_SCHEDULE: the message is delivered for a specific vehicle journey when a scheduling date happens at a station (e.g. estimated arrival time)   ON_EVENT: the message is delivered for a vehicle journey when an event specified in _eventType_ (e.g. ARRIVING) happens for a station defined in _stations_
   */
  public enum DeliveryTypeEnum {
    NOW("NOW"),
    
    DELIVERY_AT("DELIVERY_AT"),
    
    REPEAT_EVERY("REPEAT_EVERY"),
    
    ON_EVENT("ON_EVENT"),
    
    ON_SCHEDULE("ON_SCHEDULE");

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_TYPE = "deliveryType";
  private DeliveryTypeEnum deliveryType;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  private String startTime;

  public static final String JSON_PROPERTY_DELIVERY_AT = "deliveryAt";
  private String deliveryAt;

  public static final String JSON_PROPERTY_REPEAT_EVERY = "repeatEvery";
  private Integer repeatEvery;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  private String endTime;

  /**
   * Event type on which message is delivered when _deliveryType_ is ON_EVENT
   */
  public enum EventTypeEnum {
    ARRIVING("ARRIVING"),
    
    DEPARTING("DEPARTING");

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  private EventTypeEnum eventType;

  public static final String JSON_PROPERTY_END_DATE_TIME = "endDateTime";
  private String endDateTime;

  public static final String JSON_PROPERTY_REPETITIONS = "repetitions";
  private Integer repetitions;

  public PassengerInformationAudioDeliveryRules() {
  }

  public PassengerInformationAudioDeliveryRules startDateTime(String startDateTime) {
    
    this.startDateTime = startDateTime;
    return this;
  }

   /**
   * Audio delivery start date
   * @return startDateTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartDateTime() {
    return startDateTime;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDateTime(String startDateTime) {
    this.startDateTime = startDateTime;
  }


  public PassengerInformationAudioDeliveryRules weekDays(List<WeekDaysEnum> weekDays) {
    
    this.weekDays = weekDays;
    return this;
  }

  public PassengerInformationAudioDeliveryRules addWeekDaysItem(WeekDaysEnum weekDaysItem) {
    if (this.weekDays == null) {
      this.weekDays = new ArrayList<>();
    }
    this.weekDays.add(weekDaysItem);
    return this;
  }

   /**
   * Days of week on which audio is delivered
   * @return weekDays
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEEK_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<WeekDaysEnum> getWeekDays() {
    return weekDays;
  }


  @JsonProperty(JSON_PROPERTY_WEEK_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeekDays(List<WeekDaysEnum> weekDays) {
    this.weekDays = weekDays;
  }


  public PassengerInformationAudioDeliveryRules deliveryType(DeliveryTypeEnum deliveryType) {
    
    this.deliveryType = deliveryType;
    return this;
  }

   /**
   * NOW: the message is delivered at the time of insertion   DELIVERY_AT: the message is delivered on the date-time _deliveryAt_   REPEAT_EVERY: the message is delivered from _startDateTime_ at _startTime_ to _endDateTime_ at _endTime_ evaluating the repetition conditions and _weekDays_ conditions   ON_SCHEDULE: the message is delivered for a specific vehicle journey when a scheduling date happens at a station (e.g. estimated arrival time)   ON_EVENT: the message is delivered for a vehicle journey when an event specified in _eventType_ (e.g. ARRIVING) happens for a station defined in _stations_
   * @return deliveryType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryType(DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public PassengerInformationAudioDeliveryRules startTime(String startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * Audio delivery start time
   * @return startTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }


  public PassengerInformationAudioDeliveryRules deliveryAt(String deliveryAt) {
    
    this.deliveryAt = deliveryAt;
    return this;
  }

   /**
   * Date and time on which message is delivered when _deliveryType_ is DELIVERY_AT
   * @return deliveryAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeliveryAt() {
    return deliveryAt;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryAt(String deliveryAt) {
    this.deliveryAt = deliveryAt;
  }


  public PassengerInformationAudioDeliveryRules repeatEvery(Integer repeatEvery) {
    
    this.repeatEvery = repeatEvery;
    return this;
  }

   /**
   * Period of time in minutes between repetitions of message when  _deliveryType_ is REPEAT_EVERY
   * @return repeatEvery
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPEAT_EVERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRepeatEvery() {
    return repeatEvery;
  }


  @JsonProperty(JSON_PROPERTY_REPEAT_EVERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepeatEvery(Integer repeatEvery) {
    this.repeatEvery = repeatEvery;
  }


  public PassengerInformationAudioDeliveryRules endTime(String endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * Audio delivery end time
   * @return endTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndTime() {
    return endTime;
  }


  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  public PassengerInformationAudioDeliveryRules eventType(EventTypeEnum eventType) {
    
    this.eventType = eventType;
    return this;
  }

   /**
   * Event type on which message is delivered when _deliveryType_ is ON_EVENT
   * @return eventType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventTypeEnum getEventType() {
    return eventType;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  public PassengerInformationAudioDeliveryRules endDateTime(String endDateTime) {
    
    this.endDateTime = endDateTime;
    return this;
  }

   /**
   * Audio delivery end date
   * @return endDateTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndDateTime() {
    return endDateTime;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDateTime(String endDateTime) {
    this.endDateTime = endDateTime;
  }


  public PassengerInformationAudioDeliveryRules repetitions(Integer repetitions) {
    
    this.repetitions = repetitions;
    return this;
  }

   /**
   * Number of times message is repeated on each occurrence when  _deliveryType_ is REPEAT_EVERY
   * @return repetitions
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPETITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRepetitions() {
    return repetitions;
  }


  @JsonProperty(JSON_PROPERTY_REPETITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepetitions(Integer repetitions) {
    this.repetitions = repetitions;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PassengerInformationAudioDeliveryRules passengerInformationAudioDeliveryRules = (PassengerInformationAudioDeliveryRules) o;
    return Objects.equals(this.startDateTime, passengerInformationAudioDeliveryRules.startDateTime) &&
        Objects.equals(this.weekDays, passengerInformationAudioDeliveryRules.weekDays) &&
        Objects.equals(this.deliveryType, passengerInformationAudioDeliveryRules.deliveryType) &&
        Objects.equals(this.startTime, passengerInformationAudioDeliveryRules.startTime) &&
        Objects.equals(this.deliveryAt, passengerInformationAudioDeliveryRules.deliveryAt) &&
        Objects.equals(this.repeatEvery, passengerInformationAudioDeliveryRules.repeatEvery) &&
        Objects.equals(this.endTime, passengerInformationAudioDeliveryRules.endTime) &&
        Objects.equals(this.eventType, passengerInformationAudioDeliveryRules.eventType) &&
        Objects.equals(this.endDateTime, passengerInformationAudioDeliveryRules.endDateTime) &&
        Objects.equals(this.repetitions, passengerInformationAudioDeliveryRules.repetitions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDateTime, weekDays, deliveryType, startTime, deliveryAt, repeatEvery, endTime, eventType, endDateTime, repetitions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PassengerInformationAudioDeliveryRules {\n");
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    weekDays: ").append(toIndentedString(weekDays)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    deliveryAt: ").append(toIndentedString(deliveryAt)).append("\n");
    sb.append("    repeatEvery: ").append(toIndentedString(repeatEvery)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    endDateTime: ").append(toIndentedString(endDateTime)).append("\n");
    sb.append("    repetitions: ").append(toIndentedString(repetitions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

