/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.Routesection;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Routeset
 */
@JsonPropertyOrder({
  Routeset.JSON_PROPERTY_VERSION,
  Routeset.JSON_PROPERTY_MESSAGE_TIME,
  Routeset.JSON_PROPERTY_TRAIN_NUMBER,
  Routeset.JSON_PROPERTY_DEPARTURE_DATE,
  Routeset.JSON_PROPERTY_ROUTE_TYPE,
  Routeset.JSON_PROPERTY_CLIENT_SYSTEM,
  Routeset.JSON_PROPERTY_MESSAGE_ID,
  Routeset.JSON_PROPERTY_ROUTESECTIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class Routeset {
  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_MESSAGE_TIME = "messageTime";
  private OffsetDateTime messageTime;

  public static final String JSON_PROPERTY_TRAIN_NUMBER = "trainNumber";
  private String trainNumber;

  public static final String JSON_PROPERTY_DEPARTURE_DATE = "departureDate";
  private LocalDate departureDate;

  public static final String JSON_PROPERTY_ROUTE_TYPE = "routeType";
  private String routeType;

  public static final String JSON_PROPERTY_CLIENT_SYSTEM = "clientSystem";
  private String clientSystem;

  public static final String JSON_PROPERTY_MESSAGE_ID = "messageId";
  private String messageId;

  public static final String JSON_PROPERTY_ROUTESECTIONS = "routesections";
  private List<Routesection> routesections;

  public Routeset() {
  }

  public Routeset version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(Long version) {
    this.version = version;
  }


  public Routeset messageTime(OffsetDateTime messageTime) {
    
    this.messageTime = messageTime;
    return this;
  }

   /**
   * Get messageTime
   * @return messageTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getMessageTime() {
    return messageTime;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessageTime(OffsetDateTime messageTime) {
    this.messageTime = messageTime;
  }


  public Routeset trainNumber(String trainNumber) {
    
    this.trainNumber = trainNumber;
    return this;
  }

   /**
   * Identifies the train inside a single departure date
   * @return trainNumber
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTrainNumber() {
    return trainNumber;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainNumber(String trainNumber) {
    this.trainNumber = trainNumber;
  }


  public Routeset departureDate(LocalDate departureDate) {
    
    this.departureDate = departureDate;
    return this;
  }

   /**
   * Date of the train&#39;s first departure
   * @return departureDate
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getDepartureDate() {
    return departureDate;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDepartureDate(LocalDate departureDate) {
    this.departureDate = departureDate;
  }


  public Routeset routeType(String routeType) {
    
    this.routeType = routeType;
    return this;
  }

   /**
   * Get routeType
   * @return routeType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROUTE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRouteType() {
    return routeType;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRouteType(String routeType) {
    this.routeType = routeType;
  }


  public Routeset clientSystem(String clientSystem) {
    
    this.clientSystem = clientSystem;
    return this;
  }

   /**
   * Get clientSystem
   * @return clientSystem
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientSystem() {
    return clientSystem;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientSystem(String clientSystem) {
    this.clientSystem = clientSystem;
  }


  public Routeset messageId(String messageId) {
    
    this.messageId = messageId;
    return this;
  }

   /**
   * Get messageId
   * @return messageId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessageId() {
    return messageId;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }


  public Routeset routesections(List<Routesection> routesections) {
    
    this.routesections = routesections;
    return this;
  }

  public Routeset addRoutesectionsItem(Routesection routesectionsItem) {
    if (this.routesections == null) {
      this.routesections = new ArrayList<>();
    }
    this.routesections.add(routesectionsItem);
    return this;
  }

   /**
   * Get routesections
   * @return routesections
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROUTESECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Routesection> getRoutesections() {
    return routesections;
  }


  @JsonProperty(JSON_PROPERTY_ROUTESECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoutesections(List<Routesection> routesections) {
    this.routesections = routesections;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Routeset routeset = (Routeset) o;
    return Objects.equals(this.version, routeset.version) &&
        Objects.equals(this.messageTime, routeset.messageTime) &&
        Objects.equals(this.trainNumber, routeset.trainNumber) &&
        Objects.equals(this.departureDate, routeset.departureDate) &&
        Objects.equals(this.routeType, routeset.routeType) &&
        Objects.equals(this.clientSystem, routeset.clientSystem) &&
        Objects.equals(this.messageId, routeset.messageId) &&
        Objects.equals(this.routesections, routeset.routesections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, messageTime, trainNumber, departureDate, routeType, clientSystem, messageId, routesections);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Routeset {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    messageTime: ").append(toIndentedString(messageTime)).append("\n");
    sb.append("    trainNumber: ").append(toIndentedString(trainNumber)).append("\n");
    sb.append("    departureDate: ").append(toIndentedString(departureDate)).append("\n");
    sb.append("    routeType: ").append(toIndentedString(routeType)).append("\n");
    sb.append("    clientSystem: ").append(toIndentedString(clientSystem)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    routesections: ").append(toIndentedString(routesections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

