/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Routesection
 */
@JsonPropertyOrder({
  Routesection.JSON_PROPERTY_SECTION_ID,
  Routesection.JSON_PROPERTY_STATION_CODE,
  Routesection.JSON_PROPERTY_COMMERCIAL_TRACK_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class Routesection {
  public static final String JSON_PROPERTY_SECTION_ID = "sectionId";
  private String sectionId;

  public static final String JSON_PROPERTY_STATION_CODE = "stationCode";
  private String stationCode;

  public static final String JSON_PROPERTY_COMMERCIAL_TRACK_ID = "commercialTrackId";
  private String commercialTrackId;

  public Routesection() {
  }

  public Routesection sectionId(String sectionId) {
    
    this.sectionId = sectionId;
    return this;
  }

   /**
   * Get sectionId
   * @return sectionId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSectionId() {
    return sectionId;
  }


  @JsonProperty(JSON_PROPERTY_SECTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSectionId(String sectionId) {
    this.sectionId = sectionId;
  }


  public Routesection stationCode(String stationCode) {
    
    this.stationCode = stationCode;
    return this;
  }

   /**
   * Get stationCode
   * @return stationCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStationCode() {
    return stationCode;
  }


  @JsonProperty(JSON_PROPERTY_STATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStationCode(String stationCode) {
    this.stationCode = stationCode;
  }


  public Routesection commercialTrackId(String commercialTrackId) {
    
    this.commercialTrackId = commercialTrackId;
    return this;
  }

   /**
   * Get commercialTrackId
   * @return commercialTrackId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMERCIAL_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommercialTrackId() {
    return commercialTrackId;
  }


  @JsonProperty(JSON_PROPERTY_COMMERCIAL_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommercialTrackId(String commercialTrackId) {
    this.commercialTrackId = commercialTrackId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Routesection routesection = (Routesection) o;
    return Objects.equals(this.sectionId, routesection.sectionId) &&
        Objects.equals(this.stationCode, routesection.stationCode) &&
        Objects.equals(this.commercialTrackId, routesection.commercialTrackId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sectionId, stationCode, commercialTrackId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Routesection {\n");
    sb.append("    sectionId: ").append(toIndentedString(sectionId)).append("\n");
    sb.append("    stationCode: ").append(toIndentedString(stationCode)).append("\n");
    sb.append("    commercialTrackId: ").append(toIndentedString(commercialTrackId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

