/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Location of work, either an operating point or a section between operating points
 */
@JsonPropertyOrder({
  RumaLocation.JSON_PROPERTY_NOTIFICATION_ID,
  RumaLocation.JSON_PROPERTY_WORK_PART_INDEX,
  RumaLocation.JSON_PROPERTY_LOCATION_TYPE,
  RumaLocation.JSON_PROPERTY_OPERATING_POINT_ID,
  RumaLocation.JSON_PROPERTY_SECTION_BETWEEN_OPERATING_POINTS_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class RumaLocation {
  public static final String JSON_PROPERTY_NOTIFICATION_ID = "notificationId";
  private String notificationId;

  public static final String JSON_PROPERTY_WORK_PART_INDEX = "workPartIndex";
  private Long workPartIndex;

  /**
   * Type
   */
  public enum LocationTypeEnum {
    WORK("WORK"),
    
    FIREWORK("FIREWORK"),
    
    SPEED_LIMIT("SPEED_LIMIT");

    private String value;

    LocationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LocationTypeEnum fromValue(String value) {
      for (LocationTypeEnum b : LocationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LOCATION_TYPE = "locationType";
  private LocationTypeEnum locationType;

  public static final String JSON_PROPERTY_OPERATING_POINT_ID = "operatingPointId";
  private String operatingPointId;

  public static final String JSON_PROPERTY_SECTION_BETWEEN_OPERATING_POINTS_ID = "sectionBetweenOperatingPointsId";
  private String sectionBetweenOperatingPointsId;

  public RumaLocation() {
  }

  public RumaLocation notificationId(String notificationId) {
    
    this.notificationId = notificationId;
    return this;
  }

   /**
   * Notification identifier
   * @return notificationId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NOTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNotificationId() {
    return notificationId;
  }


  @JsonProperty(JSON_PROPERTY_NOTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotificationId(String notificationId) {
    this.notificationId = notificationId;
  }


  public RumaLocation workPartIndex(Long workPartIndex) {
    
    this.workPartIndex = workPartIndex;
    return this;
  }

   /**
   * Track work part index
   * @return workPartIndex
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WORK_PART_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getWorkPartIndex() {
    return workPartIndex;
  }


  @JsonProperty(JSON_PROPERTY_WORK_PART_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkPartIndex(Long workPartIndex) {
    this.workPartIndex = workPartIndex;
  }


  public RumaLocation locationType(LocationTypeEnum locationType) {
    
    this.locationType = locationType;
    return this;
  }

   /**
   * Type
   * @return locationType
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocationTypeEnum getLocationType() {
    return locationType;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocationType(LocationTypeEnum locationType) {
    this.locationType = locationType;
  }


  public RumaLocation operatingPointId(String operatingPointId) {
    
    this.operatingPointId = operatingPointId;
    return this;
  }

   /**
   * Identifier of operating point, required if section is not present
   * @return operatingPointId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATING_POINT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperatingPointId() {
    return operatingPointId;
  }


  @JsonProperty(JSON_PROPERTY_OPERATING_POINT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatingPointId(String operatingPointId) {
    this.operatingPointId = operatingPointId;
  }


  public RumaLocation sectionBetweenOperatingPointsId(String sectionBetweenOperatingPointsId) {
    
    this.sectionBetweenOperatingPointsId = sectionBetweenOperatingPointsId;
    return this;
  }

   /**
   * Identifier of section between operating points, required if operating point is not present
   * @return sectionBetweenOperatingPointsId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECTION_BETWEEN_OPERATING_POINTS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSectionBetweenOperatingPointsId() {
    return sectionBetweenOperatingPointsId;
  }


  @JsonProperty(JSON_PROPERTY_SECTION_BETWEEN_OPERATING_POINTS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSectionBetweenOperatingPointsId(String sectionBetweenOperatingPointsId) {
    this.sectionBetweenOperatingPointsId = sectionBetweenOperatingPointsId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RumaLocation rumaLocation = (RumaLocation) o;
    return Objects.equals(this.notificationId, rumaLocation.notificationId) &&
        Objects.equals(this.workPartIndex, rumaLocation.workPartIndex) &&
        Objects.equals(this.locationType, rumaLocation.locationType) &&
        Objects.equals(this.operatingPointId, rumaLocation.operatingPointId) &&
        Objects.equals(this.sectionBetweenOperatingPointsId, rumaLocation.sectionBetweenOperatingPointsId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notificationId, workPartIndex, locationType, operatingPointId, sectionBetweenOperatingPointsId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RumaLocation {\n");
    sb.append("    notificationId: ").append(toIndentedString(notificationId)).append("\n");
    sb.append("    workPartIndex: ").append(toIndentedString(workPartIndex)).append("\n");
    sb.append("    locationType: ").append(toIndentedString(locationType)).append("\n");
    sb.append("    operatingPointId: ").append(toIndentedString(operatingPointId)).append("\n");
    sb.append("    sectionBetweenOperatingPointsId: ").append(toIndentedString(sectionBetweenOperatingPointsId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

