/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import fi.digitraffic.traingraph.model.SpatialRumaLocation;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Describes a restriction affecting the use of a railway infrastructure part
 */
@JsonPropertyOrder({
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_ID,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_STATE,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_ORGANIZATION,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_CREATED,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_MODIFIED,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_LIMITATION,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_TRACK_WORK_NOTIFICATION_ID,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_AXLE_WEIGHT_MAX,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_START_DATE,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_END_DATE,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_FINISHED,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_LOCATION,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_LOCATIONS,
  SpatialTrafficRestrictionNotification.JSON_PROPERTY_VERSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class SpatialTrafficRestrictionNotification {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  /**
   * State
   */
  public enum StateEnum {
    FINISHED("FINISHED"),
    
    SENT("SENT"),
    
    DRAFT("DRAFT"),
    
    REMOVED("REMOVED");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  private StateEnum state;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  private String organization;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  private OffsetDateTime modified;

  /**
   * Limitation type
   */
  public enum LimitationEnum {
    CLOSED_FROM_TRAFFIC("CLOSED_FROM_TRAFFIC"),
    
    CLOSED_FROM_ELECTRIC_ROLLING_STOCK("CLOSED_FROM_ELECTRIC_ROLLING_STOCK"),
    
    TEMPORARY_SPEED_LIMIT("TEMPORARY_SPEED_LIMIT"),
    
    AXLE_WEIGHT_MAX("AXLE_WEIGHT_MAX"),
    
    ATP_CONSTRUCTION_ZONE("ATP_CONSTRUCTION_ZONE"),
    
    SWITCH_LOCKED("SWITCH_LOCKED"),
    
    FIREWORK_DANGER_ZONE("FIREWORK_DANGER_ZONE"),
    
    OTHER("OTHER");

    private String value;

    LimitationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LimitationEnum fromValue(String value) {
      for (LimitationEnum b : LimitationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LIMITATION = "limitation";
  private LimitationEnum limitation;

  public static final String JSON_PROPERTY_TRACK_WORK_NOTIFICATION_ID = "trackWorkNotificationId";
  private String trackWorkNotificationId;

  public static final String JSON_PROPERTY_AXLE_WEIGHT_MAX = "axleWeightMax";
  private Double axleWeightMax;

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  private OffsetDateTime startDate;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  private OffsetDateTime endDate;

  public static final String JSON_PROPERTY_FINISHED = "finished";
  private OffsetDateTime finished;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private Object location;

  public static final String JSON_PROPERTY_LOCATIONS = "locations";
  private Set<SpatialRumaLocation> locations = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public SpatialTrafficRestrictionNotification() {
  }

  public SpatialTrafficRestrictionNotification id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Id
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public SpatialTrafficRestrictionNotification state(StateEnum state) {
    
    this.state = state;
    return this;
  }

   /**
   * State
   * @return state
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StateEnum getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(StateEnum state) {
    this.state = state;
  }


  public SpatialTrafficRestrictionNotification organization(String organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * Which organization created this notification
   * @return organization
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganization(String organization) {
    this.organization = organization;
  }


  public SpatialTrafficRestrictionNotification created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * When this notification was created
   * @return created
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public SpatialTrafficRestrictionNotification modified(OffsetDateTime modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * When this notification last modified
   * @return modified
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getModified() {
    return modified;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModified(OffsetDateTime modified) {
    this.modified = modified;
  }


  public SpatialTrafficRestrictionNotification limitation(LimitationEnum limitation) {
    
    this.limitation = limitation;
    return this;
  }

   /**
   * Limitation type
   * @return limitation
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LIMITATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LimitationEnum getLimitation() {
    return limitation;
  }


  @JsonProperty(JSON_PROPERTY_LIMITATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimitation(LimitationEnum limitation) {
    this.limitation = limitation;
  }


  public SpatialTrafficRestrictionNotification trackWorkNotificationId(String trackWorkNotificationId) {
    
    this.trackWorkNotificationId = trackWorkNotificationId;
    return this;
  }

   /**
   * Track work notification identifier
   * @return trackWorkNotificationId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_WORK_NOTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackWorkNotificationId() {
    return trackWorkNotificationId;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_WORK_NOTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackWorkNotificationId(String trackWorkNotificationId) {
    this.trackWorkNotificationId = trackWorkNotificationId;
  }


  public SpatialTrafficRestrictionNotification axleWeightMax(Double axleWeightMax) {
    
    this.axleWeightMax = axleWeightMax;
    return this;
  }

   /**
   * Max axle weight, required if limitation type is max axle weight
   * @return axleWeightMax
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AXLE_WEIGHT_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAxleWeightMax() {
    return axleWeightMax;
  }


  @JsonProperty(JSON_PROPERTY_AXLE_WEIGHT_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAxleWeightMax(Double axleWeightMax) {
    this.axleWeightMax = axleWeightMax;
  }


  public SpatialTrafficRestrictionNotification startDate(OffsetDateTime startDate) {
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Start datetime
   * @return startDate
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getStartDate() {
    return startDate;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }


  public SpatialTrafficRestrictionNotification endDate(OffsetDateTime endDate) {
    
    this.endDate = endDate;
    return this;
  }

   /**
   * End datetime
   * @return endDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEndDate() {
    return endDate;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }


  public SpatialTrafficRestrictionNotification finished(OffsetDateTime finished) {
    
    this.finished = finished;
    return this;
  }

   /**
   * Finished datetime, required if state is finished
   * @return finished
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getFinished() {
    return finished;
  }


  @JsonProperty(JSON_PROPERTY_FINISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinished(OffsetDateTime finished) {
    this.finished = finished;
  }


  public SpatialTrafficRestrictionNotification location(Object location) {
    
    this.location = location;
    return this;
  }

   /**
   * Approximate location
   * @return location
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(Object location) {
    this.location = location;
  }


  public SpatialTrafficRestrictionNotification locations(Set<SpatialRumaLocation> locations) {
    
    this.locations = locations;
    return this;
  }

  public SpatialTrafficRestrictionNotification addLocationsItem(SpatialRumaLocation locationsItem) {
    if (this.locations == null) {
      this.locations = new LinkedHashSet<>();
    }
    this.locations.add(locationsItem);
    return this;
  }

   /**
   * Locations
   * @return locations
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Set<SpatialRumaLocation> getLocations() {
    return locations;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocations(Set<SpatialRumaLocation> locations) {
    this.locations = locations;
  }


  public SpatialTrafficRestrictionNotification version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * Version
   * @return version
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(Long version) {
    this.version = version;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpatialTrafficRestrictionNotification spatialTrafficRestrictionNotification = (SpatialTrafficRestrictionNotification) o;
    return Objects.equals(this.id, spatialTrafficRestrictionNotification.id) &&
        Objects.equals(this.state, spatialTrafficRestrictionNotification.state) &&
        Objects.equals(this.organization, spatialTrafficRestrictionNotification.organization) &&
        Objects.equals(this.created, spatialTrafficRestrictionNotification.created) &&
        Objects.equals(this.modified, spatialTrafficRestrictionNotification.modified) &&
        Objects.equals(this.limitation, spatialTrafficRestrictionNotification.limitation) &&
        Objects.equals(this.trackWorkNotificationId, spatialTrafficRestrictionNotification.trackWorkNotificationId) &&
        Objects.equals(this.axleWeightMax, spatialTrafficRestrictionNotification.axleWeightMax) &&
        Objects.equals(this.startDate, spatialTrafficRestrictionNotification.startDate) &&
        Objects.equals(this.endDate, spatialTrafficRestrictionNotification.endDate) &&
        Objects.equals(this.finished, spatialTrafficRestrictionNotification.finished) &&
        Objects.equals(this.location, spatialTrafficRestrictionNotification.location) &&
        Objects.equals(this.locations, spatialTrafficRestrictionNotification.locations) &&
        Objects.equals(this.version, spatialTrafficRestrictionNotification.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, state, organization, created, modified, limitation, trackWorkNotificationId, axleWeightMax, startDate, endDate, finished, location, locations, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpatialTrafficRestrictionNotification {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    limitation: ").append(toIndentedString(limitation)).append("\n");
    sb.append("    trackWorkNotificationId: ").append(toIndentedString(trackWorkNotificationId)).append("\n");
    sb.append("    axleWeightMax: ").append(toIndentedString(axleWeightMax)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

