/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.TrackWorkPart;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Describes planned, in-progress or finished track work
 */
@JsonPropertyOrder({
  SpatialTrackWorkNotification.JSON_PROPERTY_ID,
  SpatialTrackWorkNotification.JSON_PROPERTY_STATE,
  SpatialTrackWorkNotification.JSON_PROPERTY_ORGANIZATION,
  SpatialTrackWorkNotification.JSON_PROPERTY_CREATED,
  SpatialTrackWorkNotification.JSON_PROPERTY_MODIFIED,
  SpatialTrackWorkNotification.JSON_PROPERTY_TRAFFIC_SAFETY_PLAN,
  SpatialTrackWorkNotification.JSON_PROPERTY_SPEED_LIMIT_REMOVAL_PLAN,
  SpatialTrackWorkNotification.JSON_PROPERTY_ELECTRICITY_SAFETY_PLAN,
  SpatialTrackWorkNotification.JSON_PROPERTY_SPEED_LIMIT_PLAN,
  SpatialTrackWorkNotification.JSON_PROPERTY_PERSON_IN_CHARGE_PLAN,
  SpatialTrackWorkNotification.JSON_PROPERTY_LOCATION,
  SpatialTrackWorkNotification.JSON_PROPERTY_WORK_PARTS,
  SpatialTrackWorkNotification.JSON_PROPERTY_VERSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class SpatialTrackWorkNotification {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  /**
   * State
   */
  public enum StateEnum {
    ACTIVE("ACTIVE"),
    
    PASSIVE("PASSIVE"),
    
    FINISHED("FINISHED"),
    
    SENT("SENT"),
    
    DRAFT("DRAFT"),
    
    REMOVED("REMOVED"),
    
    REJECTED("REJECTED");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  private StateEnum state;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  private String organization;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  private OffsetDateTime modified;

  public static final String JSON_PROPERTY_TRAFFIC_SAFETY_PLAN = "trafficSafetyPlan";
  private Boolean trafficSafetyPlan;

  public static final String JSON_PROPERTY_SPEED_LIMIT_REMOVAL_PLAN = "speedLimitRemovalPlan";
  private Boolean speedLimitRemovalPlan;

  public static final String JSON_PROPERTY_ELECTRICITY_SAFETY_PLAN = "electricitySafetyPlan";
  private Boolean electricitySafetyPlan;

  public static final String JSON_PROPERTY_SPEED_LIMIT_PLAN = "speedLimitPlan";
  private Boolean speedLimitPlan;

  public static final String JSON_PROPERTY_PERSON_IN_CHARGE_PLAN = "personInChargePlan";
  private Boolean personInChargePlan;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private Object location;

  public static final String JSON_PROPERTY_WORK_PARTS = "workParts";
  private List<TrackWorkPart> workParts = new ArrayList<>();

  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public SpatialTrackWorkNotification() {
  }

  public SpatialTrackWorkNotification id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Id
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public SpatialTrackWorkNotification state(StateEnum state) {
    
    this.state = state;
    return this;
  }

   /**
   * State
   * @return state
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StateEnum getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(StateEnum state) {
    this.state = state;
  }


  public SpatialTrackWorkNotification organization(String organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * Which organization created this notification
   * @return organization
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganization(String organization) {
    this.organization = organization;
  }


  public SpatialTrackWorkNotification created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * When this notification was created
   * @return created
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public SpatialTrackWorkNotification modified(OffsetDateTime modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * When this notification last modified
   * @return modified
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getModified() {
    return modified;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModified(OffsetDateTime modified) {
    this.modified = modified;
  }


  public SpatialTrackWorkNotification trafficSafetyPlan(Boolean trafficSafetyPlan) {
    
    this.trafficSafetyPlan = trafficSafetyPlan;
    return this;
  }

   /**
   * Does the notification contain a traffic safety plan
   * @return trafficSafetyPlan
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRAFFIC_SAFETY_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getTrafficSafetyPlan() {
    return trafficSafetyPlan;
  }


  @JsonProperty(JSON_PROPERTY_TRAFFIC_SAFETY_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrafficSafetyPlan(Boolean trafficSafetyPlan) {
    this.trafficSafetyPlan = trafficSafetyPlan;
  }


  public SpatialTrackWorkNotification speedLimitRemovalPlan(Boolean speedLimitRemovalPlan) {
    
    this.speedLimitRemovalPlan = speedLimitRemovalPlan;
    return this;
  }

   /**
   * Does the notification contain a speed limit removal plan
   * @return speedLimitRemovalPlan
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SPEED_LIMIT_REMOVAL_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSpeedLimitRemovalPlan() {
    return speedLimitRemovalPlan;
  }


  @JsonProperty(JSON_PROPERTY_SPEED_LIMIT_REMOVAL_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSpeedLimitRemovalPlan(Boolean speedLimitRemovalPlan) {
    this.speedLimitRemovalPlan = speedLimitRemovalPlan;
  }


  public SpatialTrackWorkNotification electricitySafetyPlan(Boolean electricitySafetyPlan) {
    
    this.electricitySafetyPlan = electricitySafetyPlan;
    return this;
  }

   /**
   * Does the notification contain a electricity safety plan
   * @return electricitySafetyPlan
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ELECTRICITY_SAFETY_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getElectricitySafetyPlan() {
    return electricitySafetyPlan;
  }


  @JsonProperty(JSON_PROPERTY_ELECTRICITY_SAFETY_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setElectricitySafetyPlan(Boolean electricitySafetyPlan) {
    this.electricitySafetyPlan = electricitySafetyPlan;
  }


  public SpatialTrackWorkNotification speedLimitPlan(Boolean speedLimitPlan) {
    
    this.speedLimitPlan = speedLimitPlan;
    return this;
  }

   /**
   * Does the notification contain a speed limit plan
   * @return speedLimitPlan
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SPEED_LIMIT_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSpeedLimitPlan() {
    return speedLimitPlan;
  }


  @JsonProperty(JSON_PROPERTY_SPEED_LIMIT_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSpeedLimitPlan(Boolean speedLimitPlan) {
    this.speedLimitPlan = speedLimitPlan;
  }


  public SpatialTrackWorkNotification personInChargePlan(Boolean personInChargePlan) {
    
    this.personInChargePlan = personInChargePlan;
    return this;
  }

   /**
   * Does the notification contain a plan for persons in charge
   * @return personInChargePlan
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERSON_IN_CHARGE_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getPersonInChargePlan() {
    return personInChargePlan;
  }


  @JsonProperty(JSON_PROPERTY_PERSON_IN_CHARGE_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonInChargePlan(Boolean personInChargePlan) {
    this.personInChargePlan = personInChargePlan;
  }


  public SpatialTrackWorkNotification location(Object location) {
    
    this.location = location;
    return this;
  }

   /**
   * Approximate location
   * @return location
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(Object location) {
    this.location = location;
  }


  public SpatialTrackWorkNotification workParts(List<TrackWorkPart> workParts) {
    
    this.workParts = workParts;
    return this;
  }

  public SpatialTrackWorkNotification addWorkPartsItem(TrackWorkPart workPartsItem) {
    if (this.workParts == null) {
      this.workParts = new ArrayList<>();
    }
    this.workParts.add(workPartsItem);
    return this;
  }

   /**
   * Work parts
   * @return workParts
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WORK_PARTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<TrackWorkPart> getWorkParts() {
    return workParts;
  }


  @JsonProperty(JSON_PROPERTY_WORK_PARTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkParts(List<TrackWorkPart> workParts) {
    this.workParts = workParts;
  }


  public SpatialTrackWorkNotification version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * Version
   * @return version
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(Long version) {
    this.version = version;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpatialTrackWorkNotification spatialTrackWorkNotification = (SpatialTrackWorkNotification) o;
    return Objects.equals(this.id, spatialTrackWorkNotification.id) &&
        Objects.equals(this.state, spatialTrackWorkNotification.state) &&
        Objects.equals(this.organization, spatialTrackWorkNotification.organization) &&
        Objects.equals(this.created, spatialTrackWorkNotification.created) &&
        Objects.equals(this.modified, spatialTrackWorkNotification.modified) &&
        Objects.equals(this.trafficSafetyPlan, spatialTrackWorkNotification.trafficSafetyPlan) &&
        Objects.equals(this.speedLimitRemovalPlan, spatialTrackWorkNotification.speedLimitRemovalPlan) &&
        Objects.equals(this.electricitySafetyPlan, spatialTrackWorkNotification.electricitySafetyPlan) &&
        Objects.equals(this.speedLimitPlan, spatialTrackWorkNotification.speedLimitPlan) &&
        Objects.equals(this.personInChargePlan, spatialTrackWorkNotification.personInChargePlan) &&
        Objects.equals(this.location, spatialTrackWorkNotification.location) &&
        Objects.equals(this.workParts, spatialTrackWorkNotification.workParts) &&
        Objects.equals(this.version, spatialTrackWorkNotification.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, state, organization, created, modified, trafficSafetyPlan, speedLimitRemovalPlan, electricitySafetyPlan, speedLimitPlan, personInChargePlan, location, workParts, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpatialTrackWorkNotification {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    trafficSafetyPlan: ").append(toIndentedString(trafficSafetyPlan)).append("\n");
    sb.append("    speedLimitRemovalPlan: ").append(toIndentedString(speedLimitRemovalPlan)).append("\n");
    sb.append("    electricitySafetyPlan: ").append(toIndentedString(electricitySafetyPlan)).append("\n");
    sb.append("    speedLimitPlan: ").append(toIndentedString(speedLimitPlan)).append("\n");
    sb.append("    personInChargePlan: ").append(toIndentedString(personInChargePlan)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    workParts: ").append(toIndentedString(workParts)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

