/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Speed limit set for a part of a track
 */
@JsonPropertyOrder({
  SpeedLimit.JSON_PROPERTY_SPEED,
  SpeedLimit.JSON_PROPERTY_SIGNS,
  SpeedLimit.JSON_PROPERTY_BALISES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class SpeedLimit {
  public static final String JSON_PROPERTY_SPEED = "speed";
  private Integer speed;

  public static final String JSON_PROPERTY_SIGNS = "signs";
  private Boolean signs;

  public static final String JSON_PROPERTY_BALISES = "balises";
  private Boolean balises;

  public SpeedLimit() {
  }

  public SpeedLimit speed(Integer speed) {
    
    this.speed = speed;
    return this;
  }

   /**
   * Speed limit value
   * @return speed
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SPEED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSpeed() {
    return speed;
  }


  @JsonProperty(JSON_PROPERTY_SPEED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSpeed(Integer speed) {
    this.speed = speed;
  }


  public SpeedLimit signs(Boolean signs) {
    
    this.signs = signs;
    return this;
  }

   /**
   * Speed limit signs used?
   * @return signs
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSigns() {
    return signs;
  }


  @JsonProperty(JSON_PROPERTY_SIGNS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSigns(Boolean signs) {
    this.signs = signs;
  }


  public SpeedLimit balises(Boolean balises) {
    
    this.balises = balises;
    return this;
  }

   /**
   * Balises used?
   * @return balises
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BALISES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getBalises() {
    return balises;
  }


  @JsonProperty(JSON_PROPERTY_BALISES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBalises(Boolean balises) {
    this.balises = balises;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpeedLimit speedLimit = (SpeedLimit) o;
    return Objects.equals(this.speed, speedLimit.speed) &&
        Objects.equals(this.signs, speedLimit.signs) &&
        Objects.equals(this.balises, speedLimit.balises);
  }

  @Override
  public int hashCode() {
    return Objects.hash(speed, signs, balises);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpeedLimit {\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    signs: ").append(toIndentedString(signs)).append("\n");
    sb.append("    balises: ").append(toIndentedString(balises)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

