/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Station
 */
@JsonPropertyOrder({
  Station.JSON_PROPERTY_PASSENGER_TRAFFIC,
  Station.JSON_PROPERTY_TYPE,
  Station.JSON_PROPERTY_STATION_NAME,
  Station.JSON_PROPERTY_STATION_SHORT_CODE,
  Station.JSON_PROPERTY_STATION_U_I_C_CODE,
  Station.JSON_PROPERTY_COUNTRY_CODE,
  Station.JSON_PROPERTY_LONGITUDE,
  Station.JSON_PROPERTY_LATITUDE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class Station {
  public static final String JSON_PROPERTY_PASSENGER_TRAFFIC = "passengerTraffic";
  private Boolean passengerTraffic;

  /**
   * Type of station
   */
  public enum TypeEnum {
    STATION("STATION"),
    
    STOPPING_POINT("STOPPING_POINT"),
    
    TURNOUT_IN_THE_OPEN_LINE("TURNOUT_IN_THE_OPEN_LINE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_STATION_NAME = "stationName";
  private String stationName;

  public static final String JSON_PROPERTY_STATION_SHORT_CODE = "stationShortCode";
  private String stationShortCode;

  public static final String JSON_PROPERTY_STATION_U_I_C_CODE = "stationUICCode";
  private Integer stationUICCode;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "countryCode";
  private String countryCode;

  public static final String JSON_PROPERTY_LONGITUDE = "longitude";
  private BigDecimal longitude;

  public static final String JSON_PROPERTY_LATITUDE = "latitude";
  private BigDecimal latitude;

  public Station() {
  }

  public Station passengerTraffic(Boolean passengerTraffic) {
    
    this.passengerTraffic = passengerTraffic;
    return this;
  }

   /**
   * Does this station have passenger traffic
   * @return passengerTraffic
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSENGER_TRAFFIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPassengerTraffic() {
    return passengerTraffic;
  }


  @JsonProperty(JSON_PROPERTY_PASSENGER_TRAFFIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassengerTraffic(Boolean passengerTraffic) {
    this.passengerTraffic = passengerTraffic;
  }


  public Station type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of station
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public Station stationName(String stationName) {
    
    this.stationName = stationName;
    return this;
  }

   /**
   * Get stationName
   * @return stationName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStationName() {
    return stationName;
  }


  @JsonProperty(JSON_PROPERTY_STATION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStationName(String stationName) {
    this.stationName = stationName;
  }


  public Station stationShortCode(String stationShortCode) {
    
    this.stationShortCode = stationShortCode;
    return this;
  }

   /**
   * Get stationShortCode
   * @return stationShortCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStationShortCode() {
    return stationShortCode;
  }


  @JsonProperty(JSON_PROPERTY_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStationShortCode(String stationShortCode) {
    this.stationShortCode = stationShortCode;
  }


  public Station stationUICCode(Integer stationUICCode) {
    
    this.stationUICCode = stationUICCode;
    return this;
  }

   /**
   * Get stationUICCode
   * @return stationUICCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStationUICCode() {
    return stationUICCode;
  }


  @JsonProperty(JSON_PROPERTY_STATION_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStationUICCode(Integer stationUICCode) {
    this.stationUICCode = stationUICCode;
  }


  public Station countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public Station longitude(BigDecimal longitude) {
    
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLongitude() {
    return longitude;
  }


  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongitude(BigDecimal longitude) {
    this.longitude = longitude;
  }


  public Station latitude(BigDecimal latitude) {
    
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLatitude() {
    return latitude;
  }


  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatitude(BigDecimal latitude) {
    this.latitude = latitude;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Station station = (Station) o;
    return Objects.equals(this.passengerTraffic, station.passengerTraffic) &&
        Objects.equals(this.type, station.type) &&
        Objects.equals(this.stationName, station.stationName) &&
        Objects.equals(this.stationShortCode, station.stationShortCode) &&
        Objects.equals(this.stationUICCode, station.stationUICCode) &&
        Objects.equals(this.countryCode, station.countryCode) &&
        Objects.equals(this.longitude, station.longitude) &&
        Objects.equals(this.latitude, station.latitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passengerTraffic, type, stationName, stationShortCode, stationUICCode, countryCode, longitude, latitude);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Station {\n");
    sb.append("    passengerTraffic: ").append(toIndentedString(passengerTraffic)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    stationName: ").append(toIndentedString(stationName)).append("\n");
    sb.append("    stationShortCode: ").append(toIndentedString(stationShortCode)).append("\n");
    sb.append("    stationUICCode: ").append(toIndentedString(stationUICCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

