/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.PassengerTerm;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Most detailed category code for a Cause
 */
@JsonPropertyOrder({
  ThirdCategoryCode.JSON_PROPERTY_PASSENGER_TERM,
  ThirdCategoryCode.JSON_PROPERTY_THIRD_CATEGORY_CODE,
  ThirdCategoryCode.JSON_PROPERTY_THIRD_CATEGORY_NAME,
  ThirdCategoryCode.JSON_PROPERTY_DESCRIPTION,
  ThirdCategoryCode.JSON_PROPERTY_VALID_FROM,
  ThirdCategoryCode.JSON_PROPERTY_VALID_TO,
  ThirdCategoryCode.JSON_PROPERTY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class ThirdCategoryCode {
  public static final String JSON_PROPERTY_PASSENGER_TERM = "passengerTerm";
  private PassengerTerm passengerTerm;

  public static final String JSON_PROPERTY_THIRD_CATEGORY_CODE = "thirdCategoryCode";
  private String thirdCategoryCode;

  public static final String JSON_PROPERTY_THIRD_CATEGORY_NAME = "thirdCategoryName";
  private String thirdCategoryName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_VALID_FROM = "validFrom";
  private LocalDate validFrom;

  public static final String JSON_PROPERTY_VALID_TO = "validTo";
  private LocalDate validTo;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public ThirdCategoryCode() {
  }

  public ThirdCategoryCode passengerTerm(PassengerTerm passengerTerm) {
    
    this.passengerTerm = passengerTerm;
    return this;
  }

   /**
   * Get passengerTerm
   * @return passengerTerm
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSENGER_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PassengerTerm getPassengerTerm() {
    return passengerTerm;
  }


  @JsonProperty(JSON_PROPERTY_PASSENGER_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassengerTerm(PassengerTerm passengerTerm) {
    this.passengerTerm = passengerTerm;
  }


  public ThirdCategoryCode thirdCategoryCode(String thirdCategoryCode) {
    
    this.thirdCategoryCode = thirdCategoryCode;
    return this;
  }

   /**
   * Get thirdCategoryCode
   * @return thirdCategoryCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getThirdCategoryCode() {
    return thirdCategoryCode;
  }


  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThirdCategoryCode(String thirdCategoryCode) {
    this.thirdCategoryCode = thirdCategoryCode;
  }


  public ThirdCategoryCode thirdCategoryName(String thirdCategoryName) {
    
    this.thirdCategoryName = thirdCategoryName;
    return this;
  }

   /**
   * Get thirdCategoryName
   * @return thirdCategoryName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getThirdCategoryName() {
    return thirdCategoryName;
  }


  @JsonProperty(JSON_PROPERTY_THIRD_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThirdCategoryName(String thirdCategoryName) {
    this.thirdCategoryName = thirdCategoryName;
  }


  public ThirdCategoryCode description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Detailed description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ThirdCategoryCode validFrom(LocalDate validFrom) {
    
    this.validFrom = validFrom;
    return this;
  }

   /**
   * Start date when this category code is used
   * @return validFrom
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getValidFrom() {
    return validFrom;
  }


  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidFrom(LocalDate validFrom) {
    this.validFrom = validFrom;
  }


  public ThirdCategoryCode validTo(LocalDate validTo) {
    
    this.validTo = validTo;
    return this;
  }

   /**
   * End date when this code is used. Empty means category is used until further notice
   * @return validTo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getValidTo() {
    return validTo;
  }


  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidTo(LocalDate validTo) {
    this.validTo = validTo;
  }


  public ThirdCategoryCode id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThirdCategoryCode thirdCategoryCode = (ThirdCategoryCode) o;
    return Objects.equals(this.passengerTerm, thirdCategoryCode.passengerTerm) &&
        Objects.equals(this.thirdCategoryCode, thirdCategoryCode.thirdCategoryCode) &&
        Objects.equals(this.thirdCategoryName, thirdCategoryCode.thirdCategoryName) &&
        Objects.equals(this.description, thirdCategoryCode.description) &&
        Objects.equals(this.validFrom, thirdCategoryCode.validFrom) &&
        Objects.equals(this.validTo, thirdCategoryCode.validTo) &&
        Objects.equals(this.id, thirdCategoryCode.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passengerTerm, thirdCategoryCode, thirdCategoryName, description, validFrom, validTo, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThirdCategoryCode {\n");
    sb.append("    passengerTerm: ").append(toIndentedString(passengerTerm)).append("\n");
    sb.append("    thirdCategoryCode: ").append(toIndentedString(thirdCategoryCode)).append("\n");
    sb.append("    thirdCategoryName: ").append(toIndentedString(thirdCategoryName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

