/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.TimeTablePeriodChangeDate;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TimeTablePeriod
 */
@JsonPropertyOrder({
  TimeTablePeriod.JSON_PROPERTY_ID,
  TimeTablePeriod.JSON_PROPERTY_NAME,
  TimeTablePeriod.JSON_PROPERTY_EFFECTIVE_FROM,
  TimeTablePeriod.JSON_PROPERTY_EFFECTIVE_TO,
  TimeTablePeriod.JSON_PROPERTY_CAPACITY_ALLOCATION_CONFIRM_DATE,
  TimeTablePeriod.JSON_PROPERTY_CAPACITY_REQUEST_SUBMISSION_DEADLINE,
  TimeTablePeriod.JSON_PROPERTY_CHANGE_DATES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TimeTablePeriod {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_EFFECTIVE_FROM = "effectiveFrom";
  private LocalDate effectiveFrom;

  public static final String JSON_PROPERTY_EFFECTIVE_TO = "effectiveTo";
  private LocalDate effectiveTo;

  public static final String JSON_PROPERTY_CAPACITY_ALLOCATION_CONFIRM_DATE = "capacityAllocationConfirmDate";
  private LocalDate capacityAllocationConfirmDate;

  public static final String JSON_PROPERTY_CAPACITY_REQUEST_SUBMISSION_DEADLINE = "capacityRequestSubmissionDeadline";
  private LocalDate capacityRequestSubmissionDeadline;

  public static final String JSON_PROPERTY_CHANGE_DATES = "changeDates";
  private List<TimeTablePeriodChangeDate> changeDates;

  public TimeTablePeriod() {
  }

  public TimeTablePeriod id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public TimeTablePeriod name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public TimeTablePeriod effectiveFrom(LocalDate effectiveFrom) {
    
    this.effectiveFrom = effectiveFrom;
    return this;
  }

   /**
   * Get effectiveFrom
   * @return effectiveFrom
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EFFECTIVE_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getEffectiveFrom() {
    return effectiveFrom;
  }


  @JsonProperty(JSON_PROPERTY_EFFECTIVE_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEffectiveFrom(LocalDate effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
  }


  public TimeTablePeriod effectiveTo(LocalDate effectiveTo) {
    
    this.effectiveTo = effectiveTo;
    return this;
  }

   /**
   * Get effectiveTo
   * @return effectiveTo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EFFECTIVE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getEffectiveTo() {
    return effectiveTo;
  }


  @JsonProperty(JSON_PROPERTY_EFFECTIVE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEffectiveTo(LocalDate effectiveTo) {
    this.effectiveTo = effectiveTo;
  }


  public TimeTablePeriod capacityAllocationConfirmDate(LocalDate capacityAllocationConfirmDate) {
    
    this.capacityAllocationConfirmDate = capacityAllocationConfirmDate;
    return this;
  }

   /**
   * Get capacityAllocationConfirmDate
   * @return capacityAllocationConfirmDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPACITY_ALLOCATION_CONFIRM_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getCapacityAllocationConfirmDate() {
    return capacityAllocationConfirmDate;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITY_ALLOCATION_CONFIRM_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacityAllocationConfirmDate(LocalDate capacityAllocationConfirmDate) {
    this.capacityAllocationConfirmDate = capacityAllocationConfirmDate;
  }


  public TimeTablePeriod capacityRequestSubmissionDeadline(LocalDate capacityRequestSubmissionDeadline) {
    
    this.capacityRequestSubmissionDeadline = capacityRequestSubmissionDeadline;
    return this;
  }

   /**
   * Get capacityRequestSubmissionDeadline
   * @return capacityRequestSubmissionDeadline
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPACITY_REQUEST_SUBMISSION_DEADLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getCapacityRequestSubmissionDeadline() {
    return capacityRequestSubmissionDeadline;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITY_REQUEST_SUBMISSION_DEADLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacityRequestSubmissionDeadline(LocalDate capacityRequestSubmissionDeadline) {
    this.capacityRequestSubmissionDeadline = capacityRequestSubmissionDeadline;
  }


  public TimeTablePeriod changeDates(List<TimeTablePeriodChangeDate> changeDates) {
    
    this.changeDates = changeDates;
    return this;
  }

  public TimeTablePeriod addChangeDatesItem(TimeTablePeriodChangeDate changeDatesItem) {
    if (this.changeDates == null) {
      this.changeDates = new ArrayList<>();
    }
    this.changeDates.add(changeDatesItem);
    return this;
  }

   /**
   * Get changeDates
   * @return changeDates
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANGE_DATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TimeTablePeriodChangeDate> getChangeDates() {
    return changeDates;
  }


  @JsonProperty(JSON_PROPERTY_CHANGE_DATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangeDates(List<TimeTablePeriodChangeDate> changeDates) {
    this.changeDates = changeDates;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeTablePeriod timeTablePeriod = (TimeTablePeriod) o;
    return Objects.equals(this.id, timeTablePeriod.id) &&
        Objects.equals(this.name, timeTablePeriod.name) &&
        Objects.equals(this.effectiveFrom, timeTablePeriod.effectiveFrom) &&
        Objects.equals(this.effectiveTo, timeTablePeriod.effectiveTo) &&
        Objects.equals(this.capacityAllocationConfirmDate, timeTablePeriod.capacityAllocationConfirmDate) &&
        Objects.equals(this.capacityRequestSubmissionDeadline, timeTablePeriod.capacityRequestSubmissionDeadline) &&
        Objects.equals(this.changeDates, timeTablePeriod.changeDates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, effectiveFrom, effectiveTo, capacityAllocationConfirmDate, capacityRequestSubmissionDeadline, changeDates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeTablePeriod {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    effectiveFrom: ").append(toIndentedString(effectiveFrom)).append("\n");
    sb.append("    effectiveTo: ").append(toIndentedString(effectiveTo)).append("\n");
    sb.append("    capacityAllocationConfirmDate: ").append(toIndentedString(capacityAllocationConfirmDate)).append("\n");
    sb.append("    capacityRequestSubmissionDeadline: ").append(toIndentedString(capacityRequestSubmissionDeadline)).append("\n");
    sb.append("    changeDates: ").append(toIndentedString(changeDates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

