/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TimeTablePeriodChangeDate
 */
@JsonPropertyOrder({
  TimeTablePeriodChangeDate.JSON_PROPERTY_ID,
  TimeTablePeriodChangeDate.JSON_PROPERTY_EFFECTIVE_FROM,
  TimeTablePeriodChangeDate.JSON_PROPERTY_CAPACITY_REQUEST_SUBMISSION_DEADLINE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TimeTablePeriodChangeDate {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_EFFECTIVE_FROM = "effectiveFrom";
  private LocalDate effectiveFrom;

  public static final String JSON_PROPERTY_CAPACITY_REQUEST_SUBMISSION_DEADLINE = "capacityRequestSubmissionDeadline";
  private LocalDate capacityRequestSubmissionDeadline;

  public TimeTablePeriodChangeDate() {
  }

  public TimeTablePeriodChangeDate id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public TimeTablePeriodChangeDate effectiveFrom(LocalDate effectiveFrom) {
    
    this.effectiveFrom = effectiveFrom;
    return this;
  }

   /**
   * Get effectiveFrom
   * @return effectiveFrom
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EFFECTIVE_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getEffectiveFrom() {
    return effectiveFrom;
  }


  @JsonProperty(JSON_PROPERTY_EFFECTIVE_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEffectiveFrom(LocalDate effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
  }


  public TimeTablePeriodChangeDate capacityRequestSubmissionDeadline(LocalDate capacityRequestSubmissionDeadline) {
    
    this.capacityRequestSubmissionDeadline = capacityRequestSubmissionDeadline;
    return this;
  }

   /**
   * Get capacityRequestSubmissionDeadline
   * @return capacityRequestSubmissionDeadline
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPACITY_REQUEST_SUBMISSION_DEADLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getCapacityRequestSubmissionDeadline() {
    return capacityRequestSubmissionDeadline;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITY_REQUEST_SUBMISSION_DEADLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacityRequestSubmissionDeadline(LocalDate capacityRequestSubmissionDeadline) {
    this.capacityRequestSubmissionDeadline = capacityRequestSubmissionDeadline;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeTablePeriodChangeDate timeTablePeriodChangeDate = (TimeTablePeriodChangeDate) o;
    return Objects.equals(this.id, timeTablePeriodChangeDate.id) &&
        Objects.equals(this.effectiveFrom, timeTablePeriodChangeDate.effectiveFrom) &&
        Objects.equals(this.capacityRequestSubmissionDeadline, timeTablePeriodChangeDate.capacityRequestSubmissionDeadline);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, effectiveFrom, capacityRequestSubmissionDeadline);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeTablePeriodChangeDate {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    effectiveFrom: ").append(toIndentedString(effectiveFrom)).append("\n");
    sb.append("    capacityRequestSubmissionDeadline: ").append(toIndentedString(capacityRequestSubmissionDeadline)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

