/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import fi.digitraffic.traingraph.model.Cause;
import fi.digitraffic.traingraph.model.TrainReady;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A part of train&#39;s schedule
 */
@JsonPropertyOrder({
  TimeTableRow.JSON_PROPERTY_STATION_SHORT_CODE,
  TimeTableRow.JSON_PROPERTY_STATION_U_I_C_CODE,
  TimeTableRow.JSON_PROPERTY_COUNTRY_CODE,
  TimeTableRow.JSON_PROPERTY_TYPE,
  TimeTableRow.JSON_PROPERTY_TRAIN_STOPPING,
  TimeTableRow.JSON_PROPERTY_COMMERCIAL_STOP,
  TimeTableRow.JSON_PROPERTY_CANCELLED,
  TimeTableRow.JSON_PROPERTY_SCHEDULED_TIME,
  TimeTableRow.JSON_PROPERTY_ESTIMATE_SOURCE,
  TimeTableRow.JSON_PROPERTY_UNKNOWN_DELAY,
  TimeTableRow.JSON_PROPERTY_UNKNOWN_TRACK,
  TimeTableRow.JSON_PROPERTY_ACTUAL_TIME,
  TimeTableRow.JSON_PROPERTY_DIFFERENCE_IN_MINUTES,
  TimeTableRow.JSON_PROPERTY_CAUSES,
  TimeTableRow.JSON_PROPERTY_STOP_SECTOR,
  TimeTableRow.JSON_PROPERTY_COMMERCIAL_TRACK,
  TimeTableRow.JSON_PROPERTY_LIVE_ESTIMATE_TIME,
  TimeTableRow.JSON_PROPERTY_TRAIN_READY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TimeTableRow {
  public static final String JSON_PROPERTY_STATION_SHORT_CODE = "stationShortCode";
  private String stationShortCode;

  public static final String JSON_PROPERTY_STATION_U_I_C_CODE = "stationUICCode";
  private Integer stationUICCode;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "countryCode";
  private String countryCode;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ARRIVAL("ARRIVAL"),
    
    DEPARTURE("DEPARTURE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_TRAIN_STOPPING = "trainStopping";
  private Boolean trainStopping;

  public static final String JSON_PROPERTY_COMMERCIAL_STOP = "commercialStop";
  private Boolean commercialStop;

  public static final String JSON_PROPERTY_CANCELLED = "cancelled";
  private Boolean cancelled;

  public static final String JSON_PROPERTY_SCHEDULED_TIME = "scheduledTime";
  private OffsetDateTime scheduledTime;

  /**
   * Source for the estimate
   */
  public enum EstimateSourceEnum {
    LIIKE_USER("LIIKE_USER"),
    
    MIKU_USER("MIKU_USER"),
    
    LIIKE_AUTOMATIC("LIIKE_AUTOMATIC"),
    
    UNKNOWN("UNKNOWN"),
    
    COMBOCALC("COMBOCALC");

    private String value;

    EstimateSourceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EstimateSourceEnum fromValue(String value) {
      for (EstimateSourceEnum b : EstimateSourceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ESTIMATE_SOURCE = "estimateSource";
  private EstimateSourceEnum estimateSource;

  public static final String JSON_PROPERTY_UNKNOWN_DELAY = "unknownDelay";
  private Boolean unknownDelay;

  public static final String JSON_PROPERTY_UNKNOWN_TRACK = "unknownTrack";
  private Boolean unknownTrack;

  public static final String JSON_PROPERTY_ACTUAL_TIME = "actualTime";
  private OffsetDateTime actualTime;

  public static final String JSON_PROPERTY_DIFFERENCE_IN_MINUTES = "differenceInMinutes";
  private Long differenceInMinutes;

  public static final String JSON_PROPERTY_CAUSES = "causes";
  private Set<Cause> causes;

  public static final String JSON_PROPERTY_STOP_SECTOR = "stopSector";
  private String stopSector;

  public static final String JSON_PROPERTY_COMMERCIAL_TRACK = "commercialTrack";
  private String commercialTrack;

  public static final String JSON_PROPERTY_LIVE_ESTIMATE_TIME = "liveEstimateTime";
  private OffsetDateTime liveEstimateTime;

  public static final String JSON_PROPERTY_TRAIN_READY = "trainReady";
  private TrainReady trainReady;

  public TimeTableRow() {
  }

  public TimeTableRow stationShortCode(String stationShortCode) {
    
    this.stationShortCode = stationShortCode;
    return this;
  }

   /**
   * Get stationShortCode
   * @return stationShortCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStationShortCode() {
    return stationShortCode;
  }


  @JsonProperty(JSON_PROPERTY_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStationShortCode(String stationShortCode) {
    this.stationShortCode = stationShortCode;
  }


  public TimeTableRow stationUICCode(Integer stationUICCode) {
    
    this.stationUICCode = stationUICCode;
    return this;
  }

   /**
   * Get stationUICCode
   * @return stationUICCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStationUICCode() {
    return stationUICCode;
  }


  @JsonProperty(JSON_PROPERTY_STATION_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStationUICCode(Integer stationUICCode) {
    this.stationUICCode = stationUICCode;
  }


  public TimeTableRow countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public TimeTableRow type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public TimeTableRow trainStopping(Boolean trainStopping) {
    
    this.trainStopping = trainStopping;
    return this;
  }

   /**
   * Does the train actual stop on the station
   * @return trainStopping
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_STOPPING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrainStopping() {
    return trainStopping;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_STOPPING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainStopping(Boolean trainStopping) {
    this.trainStopping = trainStopping;
  }


  public TimeTableRow commercialStop(Boolean commercialStop) {
    
    this.commercialStop = commercialStop;
    return this;
  }

   /**
   * Is the stop &#39;commercial&#39; ie. loading/unloading of passengers or cargo
   * @return commercialStop
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMERCIAL_STOP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCommercialStop() {
    return commercialStop;
  }


  @JsonProperty(JSON_PROPERTY_COMMERCIAL_STOP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommercialStop(Boolean commercialStop) {
    this.commercialStop = commercialStop;
  }


  public TimeTableRow cancelled(Boolean cancelled) {
    
    this.cancelled = cancelled;
    return this;
  }

   /**
   * Is the schedule part cancelled
   * @return cancelled
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCancelled() {
    return cancelled;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelled(Boolean cancelled) {
    this.cancelled = cancelled;
  }


  public TimeTableRow scheduledTime(OffsetDateTime scheduledTime) {
    
    this.scheduledTime = scheduledTime;
    return this;
  }

   /**
   * Scheduled time for departure/arrival of the train
   * @return scheduledTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEDULED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getScheduledTime() {
    return scheduledTime;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledTime(OffsetDateTime scheduledTime) {
    this.scheduledTime = scheduledTime;
  }


  public TimeTableRow estimateSource(EstimateSourceEnum estimateSource) {
    
    this.estimateSource = estimateSource;
    return this;
  }

   /**
   * Source for the estimate
   * @return estimateSource
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTIMATE_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EstimateSourceEnum getEstimateSource() {
    return estimateSource;
  }


  @JsonProperty(JSON_PROPERTY_ESTIMATE_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstimateSource(EstimateSourceEnum estimateSource) {
    this.estimateSource = estimateSource;
  }


  public TimeTableRow unknownDelay(Boolean unknownDelay) {
    
    this.unknownDelay = unknownDelay;
    return this;
  }

   /**
   * Set if the train is delayed, but it is impossible to estimate for how long
   * @return unknownDelay
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNKNOWN_DELAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUnknownDelay() {
    return unknownDelay;
  }


  @JsonProperty(JSON_PROPERTY_UNKNOWN_DELAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnknownDelay(Boolean unknownDelay) {
    this.unknownDelay = unknownDelay;
  }


  public TimeTableRow unknownTrack(Boolean unknownTrack) {
    
    this.unknownTrack = unknownTrack;
    return this;
  }

   /**
   * Set if the track is not known
   * @return unknownTrack
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNKNOWN_TRACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUnknownTrack() {
    return unknownTrack;
  }


  @JsonProperty(JSON_PROPERTY_UNKNOWN_TRACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnknownTrack(Boolean unknownTrack) {
    this.unknownTrack = unknownTrack;
  }


  public TimeTableRow actualTime(OffsetDateTime actualTime) {
    
    this.actualTime = actualTime;
    return this;
  }

   /**
   * Actual time when train departured or arrived on the station
   * @return actualTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTUAL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getActualTime() {
    return actualTime;
  }


  @JsonProperty(JSON_PROPERTY_ACTUAL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActualTime(OffsetDateTime actualTime) {
    this.actualTime = actualTime;
  }


  public TimeTableRow differenceInMinutes(Long differenceInMinutes) {
    
    this.differenceInMinutes = differenceInMinutes;
    return this;
  }

   /**
   * Difference between schedule and actual time in minutes
   * @return differenceInMinutes
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIFFERENCE_IN_MINUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDifferenceInMinutes() {
    return differenceInMinutes;
  }


  @JsonProperty(JSON_PROPERTY_DIFFERENCE_IN_MINUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDifferenceInMinutes(Long differenceInMinutes) {
    this.differenceInMinutes = differenceInMinutes;
  }


  public TimeTableRow causes(Set<Cause> causes) {
    
    this.causes = causes;
    return this;
  }

  public TimeTableRow addCausesItem(Cause causesItem) {
    if (this.causes == null) {
      this.causes = new LinkedHashSet<>();
    }
    this.causes.add(causesItem);
    return this;
  }

   /**
   * Get causes
   * @return causes
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<Cause> getCauses() {
    return causes;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_CAUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCauses(Set<Cause> causes) {
    this.causes = causes;
  }


  public TimeTableRow stopSector(String stopSector) {
    
    this.stopSector = stopSector;
    return this;
  }

   /**
   * Get stopSector
   * @return stopSector
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOP_SECTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStopSector() {
    return stopSector;
  }


  @JsonProperty(JSON_PROPERTY_STOP_SECTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStopSector(String stopSector) {
    this.stopSector = stopSector;
  }


  public TimeTableRow commercialTrack(String commercialTrack) {
    
    this.commercialTrack = commercialTrack;
    return this;
  }

   /**
   * Track where the train stops
   * @return commercialTrack
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMERCIAL_TRACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommercialTrack() {
    return commercialTrack;
  }


  @JsonProperty(JSON_PROPERTY_COMMERCIAL_TRACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommercialTrack(String commercialTrack) {
    this.commercialTrack = commercialTrack;
  }


  public TimeTableRow liveEstimateTime(OffsetDateTime liveEstimateTime) {
    
    this.liveEstimateTime = liveEstimateTime;
    return this;
  }

   /**
   * Estimated time for departure/arrival of the train
   * @return liveEstimateTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIVE_ESTIMATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLiveEstimateTime() {
    return liveEstimateTime;
  }


  @JsonProperty(JSON_PROPERTY_LIVE_ESTIMATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLiveEstimateTime(OffsetDateTime liveEstimateTime) {
    this.liveEstimateTime = liveEstimateTime;
  }


  public TimeTableRow trainReady(TrainReady trainReady) {
    
    this.trainReady = trainReady;
    return this;
  }

   /**
   * Get trainReady
   * @return trainReady
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_READY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TrainReady getTrainReady() {
    return trainReady;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_READY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainReady(TrainReady trainReady) {
    this.trainReady = trainReady;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeTableRow timeTableRow = (TimeTableRow) o;
    return Objects.equals(this.stationShortCode, timeTableRow.stationShortCode) &&
        Objects.equals(this.stationUICCode, timeTableRow.stationUICCode) &&
        Objects.equals(this.countryCode, timeTableRow.countryCode) &&
        Objects.equals(this.type, timeTableRow.type) &&
        Objects.equals(this.trainStopping, timeTableRow.trainStopping) &&
        Objects.equals(this.commercialStop, timeTableRow.commercialStop) &&
        Objects.equals(this.cancelled, timeTableRow.cancelled) &&
        Objects.equals(this.scheduledTime, timeTableRow.scheduledTime) &&
        Objects.equals(this.estimateSource, timeTableRow.estimateSource) &&
        Objects.equals(this.unknownDelay, timeTableRow.unknownDelay) &&
        Objects.equals(this.unknownTrack, timeTableRow.unknownTrack) &&
        Objects.equals(this.actualTime, timeTableRow.actualTime) &&
        Objects.equals(this.differenceInMinutes, timeTableRow.differenceInMinutes) &&
        Objects.equals(this.causes, timeTableRow.causes) &&
        Objects.equals(this.stopSector, timeTableRow.stopSector) &&
        Objects.equals(this.commercialTrack, timeTableRow.commercialTrack) &&
        Objects.equals(this.liveEstimateTime, timeTableRow.liveEstimateTime) &&
        Objects.equals(this.trainReady, timeTableRow.trainReady);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stationShortCode, stationUICCode, countryCode, type, trainStopping, commercialStop, cancelled, scheduledTime, estimateSource, unknownDelay, unknownTrack, actualTime, differenceInMinutes, causes, stopSector, commercialTrack, liveEstimateTime, trainReady);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeTableRow {\n");
    sb.append("    stationShortCode: ").append(toIndentedString(stationShortCode)).append("\n");
    sb.append("    stationUICCode: ").append(toIndentedString(stationUICCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    trainStopping: ").append(toIndentedString(trainStopping)).append("\n");
    sb.append("    commercialStop: ").append(toIndentedString(commercialStop)).append("\n");
    sb.append("    cancelled: ").append(toIndentedString(cancelled)).append("\n");
    sb.append("    scheduledTime: ").append(toIndentedString(scheduledTime)).append("\n");
    sb.append("    estimateSource: ").append(toIndentedString(estimateSource)).append("\n");
    sb.append("    unknownDelay: ").append(toIndentedString(unknownDelay)).append("\n");
    sb.append("    unknownTrack: ").append(toIndentedString(unknownTrack)).append("\n");
    sb.append("    actualTime: ").append(toIndentedString(actualTime)).append("\n");
    sb.append("    differenceInMinutes: ").append(toIndentedString(differenceInMinutes)).append("\n");
    sb.append("    causes: ").append(toIndentedString(causes)).append("\n");
    sb.append("    stopSector: ").append(toIndentedString(stopSector)).append("\n");
    sb.append("    commercialTrack: ").append(toIndentedString(commercialTrack)).append("\n");
    sb.append("    liveEstimateTime: ").append(toIndentedString(liveEstimateTime)).append("\n");
    sb.append("    trainReady: ").append(toIndentedString(trainReady)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

