/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import fi.digitraffic.traingraph.model.TrackRange;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TrackSection
 */
@JsonPropertyOrder({
  TrackSection.JSON_PROPERTY_ID,
  TrackSection.JSON_PROPERTY_STATION,
  TrackSection.JSON_PROPERTY_TRACK_SECTION_CODE,
  TrackSection.JSON_PROPERTY_RANGES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TrackSection {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_STATION = "station";
  private String station;

  public static final String JSON_PROPERTY_TRACK_SECTION_CODE = "trackSectionCode";
  private String trackSectionCode;

  public static final String JSON_PROPERTY_RANGES = "ranges";
  private Set<TrackRange> ranges;

  public TrackSection() {
  }

  public TrackSection id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public TrackSection station(String station) {
    
    this.station = station;
    return this;
  }

   /**
   * Get station
   * @return station
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStation() {
    return station;
  }


  @JsonProperty(JSON_PROPERTY_STATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStation(String station) {
    this.station = station;
  }


  public TrackSection trackSectionCode(String trackSectionCode) {
    
    this.trackSectionCode = trackSectionCode;
    return this;
  }

   /**
   * Get trackSectionCode
   * @return trackSectionCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_SECTION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackSectionCode() {
    return trackSectionCode;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_SECTION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackSectionCode(String trackSectionCode) {
    this.trackSectionCode = trackSectionCode;
  }


  public TrackSection ranges(Set<TrackRange> ranges) {
    
    this.ranges = ranges;
    return this;
  }

  public TrackSection addRangesItem(TrackRange rangesItem) {
    if (this.ranges == null) {
      this.ranges = new LinkedHashSet<>();
    }
    this.ranges.add(rangesItem);
    return this;
  }

   /**
   * Get ranges
   * @return ranges
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<TrackRange> getRanges() {
    return ranges;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRanges(Set<TrackRange> ranges) {
    this.ranges = ranges;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackSection trackSection = (TrackSection) o;
    return Objects.equals(this.id, trackSection.id) &&
        Objects.equals(this.station, trackSection.station) &&
        Objects.equals(this.trackSectionCode, trackSection.trackSectionCode) &&
        Objects.equals(this.ranges, trackSection.ranges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, station, trackSectionCode, ranges);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackSection {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    station: ").append(toIndentedString(station)).append("\n");
    sb.append("    trackSectionCode: ").append(toIndentedString(trackSectionCode)).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

