/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import fi.digitraffic.traingraph.model.RumaLocation;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A logical part of a track work
 */
@JsonPropertyOrder({
  TrackWorkPart.JSON_PROPERTY_PART_INDEX,
  TrackWorkPart.JSON_PROPERTY_START_DAY,
  TrackWorkPart.JSON_PROPERTY_PERMISSION_MINIMUM_DURATION,
  TrackWorkPart.JSON_PROPERTY_CONTAINS_FIRE_WORK,
  TrackWorkPart.JSON_PROPERTY_PLANNED_WORKING_GAP,
  TrackWorkPart.JSON_PROPERTY_ADVANCE_NOTIFICATIONS,
  TrackWorkPart.JSON_PROPERTY_LOCATIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TrackWorkPart {
  public static final String JSON_PROPERTY_PART_INDEX = "partIndex";
  private Long partIndex;

  public static final String JSON_PROPERTY_START_DAY = "startDay";
  private LocalDate startDay;

  public static final String JSON_PROPERTY_PERMISSION_MINIMUM_DURATION = "permissionMinimumDuration";
  private String permissionMinimumDuration;

  public static final String JSON_PROPERTY_CONTAINS_FIRE_WORK = "containsFireWork";
  private Boolean containsFireWork;

  public static final String JSON_PROPERTY_PLANNED_WORKING_GAP = "plannedWorkingGap";
  private String plannedWorkingGap;

  public static final String JSON_PROPERTY_ADVANCE_NOTIFICATIONS = "advanceNotifications";
  private List<String> advanceNotifications;

  public static final String JSON_PROPERTY_LOCATIONS = "locations";
  private Set<RumaLocation> locations = new LinkedHashSet<>();

  public TrackWorkPart() {
  }

  public TrackWorkPart partIndex(Long partIndex) {
    
    this.partIndex = partIndex;
    return this;
  }

   /**
   * Index number
   * @return partIndex
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PART_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getPartIndex() {
    return partIndex;
  }


  @JsonProperty(JSON_PROPERTY_PART_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPartIndex(Long partIndex) {
    this.partIndex = partIndex;
  }


  public TrackWorkPart startDay(LocalDate startDay) {
    
    this.startDay = startDay;
    return this;
  }

   /**
   * Planned (not necessarily actual) start day
   * @return startDay
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_START_DAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getStartDay() {
    return startDay;
  }


  @JsonProperty(JSON_PROPERTY_START_DAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartDay(LocalDate startDay) {
    this.startDay = startDay;
  }


  public TrackWorkPart permissionMinimumDuration(String permissionMinimumDuration) {
    
    this.permissionMinimumDuration = permissionMinimumDuration;
    return this;
  }

   /**
   * Requested minimum duration for work permission in ISO 8601 format, e.g. PT30M
   * @return permissionMinimumDuration
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERMISSION_MINIMUM_DURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPermissionMinimumDuration() {
    return permissionMinimumDuration;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSION_MINIMUM_DURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPermissionMinimumDuration(String permissionMinimumDuration) {
    this.permissionMinimumDuration = permissionMinimumDuration;
  }


  public TrackWorkPart containsFireWork(Boolean containsFireWork) {
    
    this.containsFireWork = containsFireWork;
    return this;
  }

   /**
   * Contains fire work
   * @return containsFireWork
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONTAINS_FIRE_WORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getContainsFireWork() {
    return containsFireWork;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_FIRE_WORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContainsFireWork(Boolean containsFireWork) {
    this.containsFireWork = containsFireWork;
  }


  public TrackWorkPart plannedWorkingGap(String plannedWorkingGap) {
    
    this.plannedWorkingGap = plannedWorkingGap;
    return this;
  }

   /**
   * Planned working gap in local time with no time zone, e.g. 11:43:00
   * @return plannedWorkingGap
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLANNED_WORKING_GAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlannedWorkingGap() {
    return plannedWorkingGap;
  }


  @JsonProperty(JSON_PROPERTY_PLANNED_WORKING_GAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlannedWorkingGap(String plannedWorkingGap) {
    this.plannedWorkingGap = plannedWorkingGap;
  }


  public TrackWorkPart advanceNotifications(List<String> advanceNotifications) {
    
    this.advanceNotifications = advanceNotifications;
    return this;
  }

  public TrackWorkPart addAdvanceNotificationsItem(String advanceNotificationsItem) {
    if (this.advanceNotifications == null) {
      this.advanceNotifications = new ArrayList<>();
    }
    this.advanceNotifications.add(advanceNotificationsItem);
    return this;
  }

   /**
   * Related advance notifications
   * @return advanceNotifications
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADVANCE_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAdvanceNotifications() {
    return advanceNotifications;
  }


  @JsonProperty(JSON_PROPERTY_ADVANCE_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdvanceNotifications(List<String> advanceNotifications) {
    this.advanceNotifications = advanceNotifications;
  }


  public TrackWorkPart locations(Set<RumaLocation> locations) {
    
    this.locations = locations;
    return this;
  }

  public TrackWorkPart addLocationsItem(RumaLocation locationsItem) {
    if (this.locations == null) {
      this.locations = new LinkedHashSet<>();
    }
    this.locations.add(locationsItem);
    return this;
  }

   /**
   * Locations
   * @return locations
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Set<RumaLocation> getLocations() {
    return locations;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocations(Set<RumaLocation> locations) {
    this.locations = locations;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackWorkPart trackWorkPart = (TrackWorkPart) o;
    return Objects.equals(this.partIndex, trackWorkPart.partIndex) &&
        Objects.equals(this.startDay, trackWorkPart.startDay) &&
        Objects.equals(this.permissionMinimumDuration, trackWorkPart.permissionMinimumDuration) &&
        Objects.equals(this.containsFireWork, trackWorkPart.containsFireWork) &&
        Objects.equals(this.plannedWorkingGap, trackWorkPart.plannedWorkingGap) &&
        Objects.equals(this.advanceNotifications, trackWorkPart.advanceNotifications) &&
        Objects.equals(this.locations, trackWorkPart.locations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partIndex, startDay, permissionMinimumDuration, containsFireWork, plannedWorkingGap, advanceNotifications, locations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackWorkPart {\n");
    sb.append("    partIndex: ").append(toIndentedString(partIndex)).append("\n");
    sb.append("    startDay: ").append(toIndentedString(startDay)).append("\n");
    sb.append("    permissionMinimumDuration: ").append(toIndentedString(permissionMinimumDuration)).append("\n");
    sb.append("    containsFireWork: ").append(toIndentedString(containsFireWork)).append("\n");
    sb.append("    plannedWorkingGap: ").append(toIndentedString(plannedWorkingGap)).append("\n");
    sb.append("    advanceNotifications: ").append(toIndentedString(advanceNotifications)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

