/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.TrackLocation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TrackRange
 */
@JsonPropertyOrder({
  TrackRange.JSON_PROPERTY_ID,
  TrackRange.JSON_PROPERTY_START_LOCATION,
  TrackRange.JSON_PROPERTY_END_LOCATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TrackRange {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_START_LOCATION = "startLocation";
  private TrackLocation startLocation;

  public static final String JSON_PROPERTY_END_LOCATION = "endLocation";
  private TrackLocation endLocation;

  public TrackRange() {
  }

  public TrackRange id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public TrackRange startLocation(TrackLocation startLocation) {
    
    this.startLocation = startLocation;
    return this;
  }

   /**
   * Get startLocation
   * @return startLocation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TrackLocation getStartLocation() {
    return startLocation;
  }


  @JsonProperty(JSON_PROPERTY_START_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartLocation(TrackLocation startLocation) {
    this.startLocation = startLocation;
  }


  public TrackRange endLocation(TrackLocation endLocation) {
    
    this.endLocation = endLocation;
    return this;
  }

   /**
   * Get endLocation
   * @return endLocation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TrackLocation getEndLocation() {
    return endLocation;
  }


  @JsonProperty(JSON_PROPERTY_END_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndLocation(TrackLocation endLocation) {
    this.endLocation = endLocation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackRange trackRange = (TrackRange) o;
    return Objects.equals(this.id, trackRange.id) &&
        Objects.equals(this.startLocation, trackRange.startLocation) &&
        Objects.equals(this.endLocation, trackRange.endLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, startLocation, endLocation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackRange {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startLocation: ").append(toIndentedString(startLocation)).append("\n");
    sb.append("    endLocation: ").append(toIndentedString(endLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

