/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A location on the track. Kilometres and meters are distance from the start of the track
 */
@JsonPropertyOrder({
  TrackLocation.JSON_PROPERTY_TRACK,
  TrackLocation.JSON_PROPERTY_KILOMETRES,
  TrackLocation.JSON_PROPERTY_METRES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TrackLocation {
  public static final String JSON_PROPERTY_TRACK = "track";
  private String track;

  public static final String JSON_PROPERTY_KILOMETRES = "kilometres";
  private Integer kilometres;

  public static final String JSON_PROPERTY_METRES = "metres";
  private Integer metres;

  public TrackLocation() {
  }

  public TrackLocation track(String track) {
    
    this.track = track;
    return this;
  }

   /**
   * Get track
   * @return track
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrack() {
    return track;
  }


  @JsonProperty(JSON_PROPERTY_TRACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrack(String track) {
    this.track = track;
  }


  public TrackLocation kilometres(Integer kilometres) {
    
    this.kilometres = kilometres;
    return this;
  }

   /**
   * Get kilometres
   * @return kilometres
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KILOMETRES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getKilometres() {
    return kilometres;
  }


  @JsonProperty(JSON_PROPERTY_KILOMETRES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKilometres(Integer kilometres) {
    this.kilometres = kilometres;
  }


  public TrackLocation metres(Integer metres) {
    
    this.metres = metres;
    return this;
  }

   /**
   * Get metres
   * @return metres
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METRES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMetres() {
    return metres;
  }


  @JsonProperty(JSON_PROPERTY_METRES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetres(Integer metres) {
    this.metres = metres;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackLocation trackLocation = (TrackLocation) o;
    return Objects.equals(this.track, trackLocation.track) &&
        Objects.equals(this.kilometres, trackLocation.kilometres) &&
        Objects.equals(this.metres, trackLocation.metres);
  }

  @Override
  public int hashCode() {
    return Objects.hash(track, kilometres, metres);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackLocation {\n");
    sb.append("    track: ").append(toIndentedString(track)).append("\n");
    sb.append("    kilometres: ").append(toIndentedString(kilometres)).append("\n");
    sb.append("    metres: ").append(toIndentedString(metres)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

