/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.TimeTableRow;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Train
 */
@JsonPropertyOrder({
  Train.JSON_PROPERTY_TRAIN_NUMBER,
  Train.JSON_PROPERTY_DEPARTURE_DATE,
  Train.JSON_PROPERTY_OPERATOR_U_I_C_CODE,
  Train.JSON_PROPERTY_OPERATOR_SHORT_CODE,
  Train.JSON_PROPERTY_TRAIN_TYPE,
  Train.JSON_PROPERTY_TRAIN_CATEGORY,
  Train.JSON_PROPERTY_COMMUTER_LINE_I_D,
  Train.JSON_PROPERTY_RUNNING_CURRENTLY,
  Train.JSON_PROPERTY_CANCELLED,
  Train.JSON_PROPERTY_DELETED,
  Train.JSON_PROPERTY_VERSION,
  Train.JSON_PROPERTY_TIMETABLE_TYPE,
  Train.JSON_PROPERTY_TIMETABLE_ACCEPTANCE_DATE,
  Train.JSON_PROPERTY_TIME_TABLE_ROWS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class Train {
  public static final String JSON_PROPERTY_TRAIN_NUMBER = "trainNumber";
  private Long trainNumber;

  public static final String JSON_PROPERTY_DEPARTURE_DATE = "departureDate";
  private LocalDate departureDate;

  public static final String JSON_PROPERTY_OPERATOR_U_I_C_CODE = "operatorUICCode";
  private Integer operatorUICCode;

  public static final String JSON_PROPERTY_OPERATOR_SHORT_CODE = "operatorShortCode";
  private String operatorShortCode;

  public static final String JSON_PROPERTY_TRAIN_TYPE = "trainType";
  private String trainType;

  public static final String JSON_PROPERTY_TRAIN_CATEGORY = "trainCategory";
  private String trainCategory;

  public static final String JSON_PROPERTY_COMMUTER_LINE_I_D = "commuterLineID";
  private String commuterLineID;

  public static final String JSON_PROPERTY_RUNNING_CURRENTLY = "runningCurrently";
  private Boolean runningCurrently;

  public static final String JSON_PROPERTY_CANCELLED = "cancelled";
  private Boolean cancelled;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  /**
   * Is the train ADHOC or REGULAR. REGULAR trains are run for example every monday, ADHOC trains are one-time trains
   */
  public enum TimetableTypeEnum {
    REGULAR("REGULAR"),
    
    ADHOC("ADHOC");

    private String value;

    TimetableTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TimetableTypeEnum fromValue(String value) {
      for (TimetableTypeEnum b : TimetableTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TIMETABLE_TYPE = "timetableType";
  private TimetableTypeEnum timetableType;

  public static final String JSON_PROPERTY_TIMETABLE_ACCEPTANCE_DATE = "timetableAcceptanceDate";
  private OffsetDateTime timetableAcceptanceDate;

  public static final String JSON_PROPERTY_TIME_TABLE_ROWS = "timeTableRows";
  private List<TimeTableRow> timeTableRows;

  public Train() {
  }

  public Train trainNumber(Long trainNumber) {
    
    this.trainNumber = trainNumber;
    return this;
  }

   /**
   * Identifies the train inside a single departure date
   * @return trainNumber
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTrainNumber() {
    return trainNumber;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainNumber(Long trainNumber) {
    this.trainNumber = trainNumber;
  }


  public Train departureDate(LocalDate departureDate) {
    
    this.departureDate = departureDate;
    return this;
  }

   /**
   * Date of the train&#39;s first departure
   * @return departureDate
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getDepartureDate() {
    return departureDate;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDepartureDate(LocalDate departureDate) {
    this.departureDate = departureDate;
  }


  public Train operatorUICCode(Integer operatorUICCode) {
    
    this.operatorUICCode = operatorUICCode;
    return this;
  }

   /**
   * Official UIC code of the operator
   * @return operatorUICCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOperatorUICCode() {
    return operatorUICCode;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR_U_I_C_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatorUICCode(Integer operatorUICCode) {
    this.operatorUICCode = operatorUICCode;
  }


  public Train operatorShortCode(String operatorShortCode) {
    
    this.operatorShortCode = operatorShortCode;
    return this;
  }

   /**
   * Short code of the operator
   * @return operatorShortCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperatorShortCode() {
    return operatorShortCode;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatorShortCode(String operatorShortCode) {
    this.operatorShortCode = operatorShortCode;
  }


  public Train trainType(String trainType) {
    
    this.trainType = trainType;
    return this;
  }

   /**
   * Get trainType
   * @return trainType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrainType() {
    return trainType;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainType(String trainType) {
    this.trainType = trainType;
  }


  public Train trainCategory(String trainCategory) {
    
    this.trainCategory = trainCategory;
    return this;
  }

   /**
   * Get trainCategory
   * @return trainCategory
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrainCategory() {
    return trainCategory;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainCategory(String trainCategory) {
    this.trainCategory = trainCategory;
  }


  public Train commuterLineID(String commuterLineID) {
    
    this.commuterLineID = commuterLineID;
    return this;
  }

   /**
   * Get commuterLineID
   * @return commuterLineID
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMUTER_LINE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommuterLineID() {
    return commuterLineID;
  }


  @JsonProperty(JSON_PROPERTY_COMMUTER_LINE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommuterLineID(String commuterLineID) {
    this.commuterLineID = commuterLineID;
  }


  public Train runningCurrently(Boolean runningCurrently) {
    
    this.runningCurrently = runningCurrently;
    return this;
  }

   /**
   * Is the train running currently or does it have actual times
   * @return runningCurrently
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RUNNING_CURRENTLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRunningCurrently() {
    return runningCurrently;
  }


  @JsonProperty(JSON_PROPERTY_RUNNING_CURRENTLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRunningCurrently(Boolean runningCurrently) {
    this.runningCurrently = runningCurrently;
  }


  public Train cancelled(Boolean cancelled) {
    
    this.cancelled = cancelled;
    return this;
  }

   /**
   * Is the train wholly cancelled
   * @return cancelled
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCancelled() {
    return cancelled;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelled(Boolean cancelled) {
    this.cancelled = cancelled;
  }


  public Train deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Is the train deleted which means cancelled 10 days before its departure date
   * @return deleted
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public Train version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * When was train last modified
   * @return version
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(Long version) {
    this.version = version;
  }


  public Train timetableType(TimetableTypeEnum timetableType) {
    
    this.timetableType = timetableType;
    return this;
  }

   /**
   * Is the train ADHOC or REGULAR. REGULAR trains are run for example every monday, ADHOC trains are one-time trains
   * @return timetableType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMETABLE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TimetableTypeEnum getTimetableType() {
    return timetableType;
  }


  @JsonProperty(JSON_PROPERTY_TIMETABLE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimetableType(TimetableTypeEnum timetableType) {
    this.timetableType = timetableType;
  }


  public Train timetableAcceptanceDate(OffsetDateTime timetableAcceptanceDate) {
    
    this.timetableAcceptanceDate = timetableAcceptanceDate;
    return this;
  }

   /**
   * When was this train accepted to run on Finnish railways by the FTA
   * @return timetableAcceptanceDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMETABLE_ACCEPTANCE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTimetableAcceptanceDate() {
    return timetableAcceptanceDate;
  }


  @JsonProperty(JSON_PROPERTY_TIMETABLE_ACCEPTANCE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimetableAcceptanceDate(OffsetDateTime timetableAcceptanceDate) {
    this.timetableAcceptanceDate = timetableAcceptanceDate;
  }


  public Train timeTableRows(List<TimeTableRow> timeTableRows) {
    
    this.timeTableRows = timeTableRows;
    return this;
  }

  public Train addTimeTableRowsItem(TimeTableRow timeTableRowsItem) {
    if (this.timeTableRows == null) {
      this.timeTableRows = new ArrayList<>();
    }
    this.timeTableRows.add(timeTableRowsItem);
    return this;
  }

   /**
   * Get timeTableRows
   * @return timeTableRows
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_TABLE_ROWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TimeTableRow> getTimeTableRows() {
    return timeTableRows;
  }


  @JsonProperty(JSON_PROPERTY_TIME_TABLE_ROWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeTableRows(List<TimeTableRow> timeTableRows) {
    this.timeTableRows = timeTableRows;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Train train = (Train) o;
    return Objects.equals(this.trainNumber, train.trainNumber) &&
        Objects.equals(this.departureDate, train.departureDate) &&
        Objects.equals(this.operatorUICCode, train.operatorUICCode) &&
        Objects.equals(this.operatorShortCode, train.operatorShortCode) &&
        Objects.equals(this.trainType, train.trainType) &&
        Objects.equals(this.trainCategory, train.trainCategory) &&
        Objects.equals(this.commuterLineID, train.commuterLineID) &&
        Objects.equals(this.runningCurrently, train.runningCurrently) &&
        Objects.equals(this.cancelled, train.cancelled) &&
        Objects.equals(this.deleted, train.deleted) &&
        Objects.equals(this.version, train.version) &&
        Objects.equals(this.timetableType, train.timetableType) &&
        Objects.equals(this.timetableAcceptanceDate, train.timetableAcceptanceDate) &&
        Objects.equals(this.timeTableRows, train.timeTableRows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trainNumber, departureDate, operatorUICCode, operatorShortCode, trainType, trainCategory, commuterLineID, runningCurrently, cancelled, deleted, version, timetableType, timetableAcceptanceDate, timeTableRows);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Train {\n");
    sb.append("    trainNumber: ").append(toIndentedString(trainNumber)).append("\n");
    sb.append("    departureDate: ").append(toIndentedString(departureDate)).append("\n");
    sb.append("    operatorUICCode: ").append(toIndentedString(operatorUICCode)).append("\n");
    sb.append("    operatorShortCode: ").append(toIndentedString(operatorShortCode)).append("\n");
    sb.append("    trainType: ").append(toIndentedString(trainType)).append("\n");
    sb.append("    trainCategory: ").append(toIndentedString(trainCategory)).append("\n");
    sb.append("    commuterLineID: ").append(toIndentedString(commuterLineID)).append("\n");
    sb.append("    runningCurrently: ").append(toIndentedString(runningCurrently)).append("\n");
    sb.append("    cancelled: ").append(toIndentedString(cancelled)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    timetableType: ").append(toIndentedString(timetableType)).append("\n");
    sb.append("    timetableAcceptanceDate: ").append(toIndentedString(timetableAcceptanceDate)).append("\n");
    sb.append("    timeTableRows: ").append(toIndentedString(timeTableRows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

