/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TrainRunMessages are generated when a train either enters or exists a TrackSection
 */
@JsonPropertyOrder({
  TrainRunningMessage.JSON_PROPERTY_ID,
  TrainRunningMessage.JSON_PROPERTY_VERSION,
  TrainRunningMessage.JSON_PROPERTY_TRAIN_NUMBER,
  TrainRunningMessage.JSON_PROPERTY_DEPARTURE_DATE,
  TrainRunningMessage.JSON_PROPERTY_TIMESTAMP,
  TrainRunningMessage.JSON_PROPERTY_TRACK_SECTION,
  TrainRunningMessage.JSON_PROPERTY_NEXT_TRACK_SECTION,
  TrainRunningMessage.JSON_PROPERTY_PREVIOUS_TRACK_SECTION,
  TrainRunningMessage.JSON_PROPERTY_STATION,
  TrainRunningMessage.JSON_PROPERTY_NEXT_STATION,
  TrainRunningMessage.JSON_PROPERTY_PREVIOUS_STATION,
  TrainRunningMessage.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TrainRunningMessage {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_TRAIN_NUMBER = "trainNumber";
  private String trainNumber;

  public static final String JSON_PROPERTY_DEPARTURE_DATE = "departureDate";
  private LocalDate departureDate;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_TRACK_SECTION = "trackSection";
  private String trackSection;

  public static final String JSON_PROPERTY_NEXT_TRACK_SECTION = "nextTrackSection";
  private String nextTrackSection;

  public static final String JSON_PROPERTY_PREVIOUS_TRACK_SECTION = "previousTrackSection";
  private String previousTrackSection;

  public static final String JSON_PROPERTY_STATION = "station";
  private String station;

  public static final String JSON_PROPERTY_NEXT_STATION = "nextStation";
  private String nextStation;

  public static final String JSON_PROPERTY_PREVIOUS_STATION = "previousStation";
  private String previousStation;

  /**
   * OCCUPY &#x3D; train entered TrackSection, RELEASE &#x3D; train exited TrackSection
   */
  public enum TypeEnum {
    OCCUPY("OCCUPY"),
    
    RELEASE("RELEASE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public TrainRunningMessage() {
  }

  public TrainRunningMessage id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public TrainRunningMessage version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(Long version) {
    this.version = version;
  }


  public TrainRunningMessage trainNumber(String trainNumber) {
    
    this.trainNumber = trainNumber;
    return this;
  }

   /**
   * Identifies the train inside a single departure date
   * @return trainNumber
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTrainNumber() {
    return trainNumber;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainNumber(String trainNumber) {
    this.trainNumber = trainNumber;
  }


  public TrainRunningMessage departureDate(LocalDate departureDate) {
    
    this.departureDate = departureDate;
    return this;
  }

   /**
   * Date of the train&#39;s first departure
   * @return departureDate
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getDepartureDate() {
    return departureDate;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDepartureDate(LocalDate departureDate) {
    this.departureDate = departureDate;
  }


  public TrainRunningMessage timestamp(OffsetDateTime timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Timestamp when the message was generated
   * @return timestamp
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public TrainRunningMessage trackSection(String trackSection) {
    
    this.trackSection = trackSection;
    return this;
  }

   /**
   * Get trackSection
   * @return trackSection
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackSection() {
    return trackSection;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackSection(String trackSection) {
    this.trackSection = trackSection;
  }


  public TrainRunningMessage nextTrackSection(String nextTrackSection) {
    
    this.nextTrackSection = nextTrackSection;
    return this;
  }

   /**
   * Get nextTrackSection
   * @return nextTrackSection
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEXT_TRACK_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextTrackSection() {
    return nextTrackSection;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_TRACK_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextTrackSection(String nextTrackSection) {
    this.nextTrackSection = nextTrackSection;
  }


  public TrainRunningMessage previousTrackSection(String previousTrackSection) {
    
    this.previousTrackSection = previousTrackSection;
    return this;
  }

   /**
   * Get previousTrackSection
   * @return previousTrackSection
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREVIOUS_TRACK_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreviousTrackSection() {
    return previousTrackSection;
  }


  @JsonProperty(JSON_PROPERTY_PREVIOUS_TRACK_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousTrackSection(String previousTrackSection) {
    this.previousTrackSection = previousTrackSection;
  }


  public TrainRunningMessage station(String station) {
    
    this.station = station;
    return this;
  }

   /**
   * Get station
   * @return station
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStation() {
    return station;
  }


  @JsonProperty(JSON_PROPERTY_STATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStation(String station) {
    this.station = station;
  }


  public TrainRunningMessage nextStation(String nextStation) {
    
    this.nextStation = nextStation;
    return this;
  }

   /**
   * Get nextStation
   * @return nextStation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEXT_STATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextStation() {
    return nextStation;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_STATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextStation(String nextStation) {
    this.nextStation = nextStation;
  }


  public TrainRunningMessage previousStation(String previousStation) {
    
    this.previousStation = previousStation;
    return this;
  }

   /**
   * Get previousStation
   * @return previousStation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREVIOUS_STATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreviousStation() {
    return previousStation;
  }


  @JsonProperty(JSON_PROPERTY_PREVIOUS_STATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousStation(String previousStation) {
    this.previousStation = previousStation;
  }


  public TrainRunningMessage type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * OCCUPY &#x3D; train entered TrackSection, RELEASE &#x3D; train exited TrackSection
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainRunningMessage trainRunningMessage = (TrainRunningMessage) o;
    return Objects.equals(this.id, trainRunningMessage.id) &&
        Objects.equals(this.version, trainRunningMessage.version) &&
        Objects.equals(this.trainNumber, trainRunningMessage.trainNumber) &&
        Objects.equals(this.departureDate, trainRunningMessage.departureDate) &&
        Objects.equals(this.timestamp, trainRunningMessage.timestamp) &&
        Objects.equals(this.trackSection, trainRunningMessage.trackSection) &&
        Objects.equals(this.nextTrackSection, trainRunningMessage.nextTrackSection) &&
        Objects.equals(this.previousTrackSection, trainRunningMessage.previousTrackSection) &&
        Objects.equals(this.station, trainRunningMessage.station) &&
        Objects.equals(this.nextStation, trainRunningMessage.nextStation) &&
        Objects.equals(this.previousStation, trainRunningMessage.previousStation) &&
        Objects.equals(this.type, trainRunningMessage.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, version, trainNumber, departureDate, timestamp, trackSection, nextTrackSection, previousTrackSection, station, nextStation, previousStation, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainRunningMessage {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    trainNumber: ").append(toIndentedString(trainNumber)).append("\n");
    sb.append("    departureDate: ").append(toIndentedString(departureDate)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    trackSection: ").append(toIndentedString(trackSection)).append("\n");
    sb.append("    nextTrackSection: ").append(toIndentedString(nextTrackSection)).append("\n");
    sb.append("    previousTrackSection: ").append(toIndentedString(previousTrackSection)).append("\n");
    sb.append("    station: ").append(toIndentedString(station)).append("\n");
    sb.append("    nextStation: ").append(toIndentedString(nextStation)).append("\n");
    sb.append("    previousStation: ").append(toIndentedString(previousStation)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

