/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * These rules define how TrainRunningMessages trigger actual times for TimeTableRows
 */
@JsonPropertyOrder({
  TrainRunningMessageRule.JSON_PROPERTY_ID,
  TrainRunningMessageRule.JSON_PROPERTY_TIME_TABLE_ROW_STATION_SHORT_CODE,
  TrainRunningMessageRule.JSON_PROPERTY_TIME_TABLE_ROW_TYPE,
  TrainRunningMessageRule.JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_STATION_SHORT_CODE,
  TrainRunningMessageRule.JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_NEXT_STATION_SHORT_CODE,
  TrainRunningMessageRule.JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_TRACK_SECTION,
  TrainRunningMessageRule.JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_TYPE,
  TrainRunningMessageRule.JSON_PROPERTY_OFFSET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TrainRunningMessageRule {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_TIME_TABLE_ROW_STATION_SHORT_CODE = "timeTableRowStationShortCode";
  private String timeTableRowStationShortCode;

  /**
   * For which TimeTableRow is the actual time generated
   */
  public enum TimeTableRowTypeEnum {
    ARRIVAL("ARRIVAL"),
    
    DEPARTURE("DEPARTURE");

    private String value;

    TimeTableRowTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TimeTableRowTypeEnum fromValue(String value) {
      for (TimeTableRowTypeEnum b : TimeTableRowTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TIME_TABLE_ROW_TYPE = "timeTableRowType";
  private TimeTableRowTypeEnum timeTableRowType;

  public static final String JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_STATION_SHORT_CODE = "trainRunningMessageStationShortCode";
  private String trainRunningMessageStationShortCode;

  public static final String JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_NEXT_STATION_SHORT_CODE = "trainRunningMessageNextStationShortCode";
  private String trainRunningMessageNextStationShortCode;

  public static final String JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_TRACK_SECTION = "trainRunningMessageTrackSection";
  private String trainRunningMessageTrackSection;

  /**
   * Gets or Sets trainRunningMessageType
   */
  public enum TrainRunningMessageTypeEnum {
    OCCUPY("OCCUPY"),
    
    RELEASE("RELEASE");

    private String value;

    TrainRunningMessageTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TrainRunningMessageTypeEnum fromValue(String value) {
      for (TrainRunningMessageTypeEnum b : TrainRunningMessageTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_TYPE = "trainRunningMessageType";
  private TrainRunningMessageTypeEnum trainRunningMessageType;

  public static final String JSON_PROPERTY_OFFSET = "offset";
  private Integer offset;

  public TrainRunningMessageRule() {
  }

  public TrainRunningMessageRule id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public TrainRunningMessageRule timeTableRowStationShortCode(String timeTableRowStationShortCode) {
    
    this.timeTableRowStationShortCode = timeTableRowStationShortCode;
    return this;
  }

   /**
   * For which station is the actual time generated
   * @return timeTableRowStationShortCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_TABLE_ROW_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeTableRowStationShortCode() {
    return timeTableRowStationShortCode;
  }


  @JsonProperty(JSON_PROPERTY_TIME_TABLE_ROW_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeTableRowStationShortCode(String timeTableRowStationShortCode) {
    this.timeTableRowStationShortCode = timeTableRowStationShortCode;
  }


  public TrainRunningMessageRule timeTableRowType(TimeTableRowTypeEnum timeTableRowType) {
    
    this.timeTableRowType = timeTableRowType;
    return this;
  }

   /**
   * For which TimeTableRow is the actual time generated
   * @return timeTableRowType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_TABLE_ROW_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TimeTableRowTypeEnum getTimeTableRowType() {
    return timeTableRowType;
  }


  @JsonProperty(JSON_PROPERTY_TIME_TABLE_ROW_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeTableRowType(TimeTableRowTypeEnum timeTableRowType) {
    this.timeTableRowType = timeTableRowType;
  }


  public TrainRunningMessageRule trainRunningMessageStationShortCode(String trainRunningMessageStationShortCode) {
    
    this.trainRunningMessageStationShortCode = trainRunningMessageStationShortCode;
    return this;
  }

   /**
   * Get trainRunningMessageStationShortCode
   * @return trainRunningMessageStationShortCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrainRunningMessageStationShortCode() {
    return trainRunningMessageStationShortCode;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainRunningMessageStationShortCode(String trainRunningMessageStationShortCode) {
    this.trainRunningMessageStationShortCode = trainRunningMessageStationShortCode;
  }


  public TrainRunningMessageRule trainRunningMessageNextStationShortCode(String trainRunningMessageNextStationShortCode) {
    
    this.trainRunningMessageNextStationShortCode = trainRunningMessageNextStationShortCode;
    return this;
  }

   /**
   * Get trainRunningMessageNextStationShortCode
   * @return trainRunningMessageNextStationShortCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_NEXT_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrainRunningMessageNextStationShortCode() {
    return trainRunningMessageNextStationShortCode;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_NEXT_STATION_SHORT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainRunningMessageNextStationShortCode(String trainRunningMessageNextStationShortCode) {
    this.trainRunningMessageNextStationShortCode = trainRunningMessageNextStationShortCode;
  }


  public TrainRunningMessageRule trainRunningMessageTrackSection(String trainRunningMessageTrackSection) {
    
    this.trainRunningMessageTrackSection = trainRunningMessageTrackSection;
    return this;
  }

   /**
   * Get trainRunningMessageTrackSection
   * @return trainRunningMessageTrackSection
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_TRACK_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrainRunningMessageTrackSection() {
    return trainRunningMessageTrackSection;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_TRACK_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainRunningMessageTrackSection(String trainRunningMessageTrackSection) {
    this.trainRunningMessageTrackSection = trainRunningMessageTrackSection;
  }


  public TrainRunningMessageRule trainRunningMessageType(TrainRunningMessageTypeEnum trainRunningMessageType) {
    
    this.trainRunningMessageType = trainRunningMessageType;
    return this;
  }

   /**
   * Get trainRunningMessageType
   * @return trainRunningMessageType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TrainRunningMessageTypeEnum getTrainRunningMessageType() {
    return trainRunningMessageType;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_RUNNING_MESSAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainRunningMessageType(TrainRunningMessageTypeEnum trainRunningMessageType) {
    this.trainRunningMessageType = trainRunningMessageType;
  }


  public TrainRunningMessageRule offset(Integer offset) {
    
    this.offset = offset;
    return this;
  }

   /**
   * TrainRunningMessages timestamp is adjusted for offset when generating actual time
   * @return offset
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOffset() {
    return offset;
  }


  @JsonProperty(JSON_PROPERTY_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainRunningMessageRule trainRunningMessageRule = (TrainRunningMessageRule) o;
    return Objects.equals(this.id, trainRunningMessageRule.id) &&
        Objects.equals(this.timeTableRowStationShortCode, trainRunningMessageRule.timeTableRowStationShortCode) &&
        Objects.equals(this.timeTableRowType, trainRunningMessageRule.timeTableRowType) &&
        Objects.equals(this.trainRunningMessageStationShortCode, trainRunningMessageRule.trainRunningMessageStationShortCode) &&
        Objects.equals(this.trainRunningMessageNextStationShortCode, trainRunningMessageRule.trainRunningMessageNextStationShortCode) &&
        Objects.equals(this.trainRunningMessageTrackSection, trainRunningMessageRule.trainRunningMessageTrackSection) &&
        Objects.equals(this.trainRunningMessageType, trainRunningMessageRule.trainRunningMessageType) &&
        Objects.equals(this.offset, trainRunningMessageRule.offset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, timeTableRowStationShortCode, timeTableRowType, trainRunningMessageStationShortCode, trainRunningMessageNextStationShortCode, trainRunningMessageTrackSection, trainRunningMessageType, offset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainRunningMessageRule {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    timeTableRowStationShortCode: ").append(toIndentedString(timeTableRowStationShortCode)).append("\n");
    sb.append("    timeTableRowType: ").append(toIndentedString(timeTableRowType)).append("\n");
    sb.append("    trainRunningMessageStationShortCode: ").append(toIndentedString(trainRunningMessageStationShortCode)).append("\n");
    sb.append("    trainRunningMessageNextStationShortCode: ").append(toIndentedString(trainRunningMessageNextStationShortCode)).append("\n");
    sb.append("    trainRunningMessageTrackSection: ").append(toIndentedString(trainRunningMessageTrackSection)).append("\n");
    sb.append("    trainRunningMessageType: ").append(toIndentedString(trainRunningMessageType)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

