/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.digitraffic.traingraph.model.SwaggerPoint;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TrainLocation
 */
@JsonPropertyOrder({
  TrainLocation.JSON_PROPERTY_TRAIN_NUMBER,
  TrainLocation.JSON_PROPERTY_DEPARTURE_DATE,
  TrainLocation.JSON_PROPERTY_TIMESTAMP,
  TrainLocation.JSON_PROPERTY_SWAGGER_POINT,
  TrainLocation.JSON_PROPERTY_SPEED,
  TrainLocation.JSON_PROPERTY_ACCURACY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class TrainLocation {
  public static final String JSON_PROPERTY_TRAIN_NUMBER = "trainNumber";
  private Long trainNumber;

  public static final String JSON_PROPERTY_DEPARTURE_DATE = "departureDate";
  private LocalDate departureDate;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_SWAGGER_POINT = "SwaggerPoint";
  private SwaggerPoint swaggerPoint;

  public static final String JSON_PROPERTY_SPEED = "speed";
  private Integer speed;

  public static final String JSON_PROPERTY_ACCURACY = "accuracy";
  private Integer accuracy;

  public TrainLocation() {
  }

  public TrainLocation trainNumber(Long trainNumber) {
    
    this.trainNumber = trainNumber;
    return this;
  }

   /**
   * Get trainNumber
   * @return trainNumber
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTrainNumber() {
    return trainNumber;
  }


  @JsonProperty(JSON_PROPERTY_TRAIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrainNumber(Long trainNumber) {
    this.trainNumber = trainNumber;
  }


  public TrainLocation departureDate(LocalDate departureDate) {
    
    this.departureDate = departureDate;
    return this;
  }

   /**
   * Get departureDate
   * @return departureDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDepartureDate() {
    return departureDate;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTURE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDepartureDate(LocalDate departureDate) {
    this.departureDate = departureDate;
  }


  public TrainLocation timestamp(OffsetDateTime timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public TrainLocation swaggerPoint(SwaggerPoint swaggerPoint) {
    
    this.swaggerPoint = swaggerPoint;
    return this;
  }

   /**
   * Get swaggerPoint
   * @return swaggerPoint
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SWAGGER_POINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SwaggerPoint getSwaggerPoint() {
    return swaggerPoint;
  }


  @JsonProperty(JSON_PROPERTY_SWAGGER_POINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSwaggerPoint(SwaggerPoint swaggerPoint) {
    this.swaggerPoint = swaggerPoint;
  }


  public TrainLocation speed(Integer speed) {
    
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSpeed() {
    return speed;
  }


  @JsonProperty(JSON_PROPERTY_SPEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpeed(Integer speed) {
    this.speed = speed;
  }


  public TrainLocation accuracy(Integer accuracy) {
    
    this.accuracy = accuracy;
    return this;
  }

   /**
   * Get accuracy
   * @return accuracy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCURACY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAccuracy() {
    return accuracy;
  }


  @JsonProperty(JSON_PROPERTY_ACCURACY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccuracy(Integer accuracy) {
    this.accuracy = accuracy;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainLocation trainLocation = (TrainLocation) o;
    return Objects.equals(this.trainNumber, trainLocation.trainNumber) &&
        Objects.equals(this.departureDate, trainLocation.departureDate) &&
        Objects.equals(this.timestamp, trainLocation.timestamp) &&
        Objects.equals(this.swaggerPoint, trainLocation.swaggerPoint) &&
        Objects.equals(this.speed, trainLocation.speed) &&
        Objects.equals(this.accuracy, trainLocation.accuracy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trainNumber, departureDate, timestamp, swaggerPoint, speed, accuracy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainLocation {\n");
    sb.append("    trainNumber: ").append(toIndentedString(trainNumber)).append("\n");
    sb.append("    departureDate: ").append(toIndentedString(departureDate)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    swaggerPoint: ").append(toIndentedString(swaggerPoint)).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    accuracy: ").append(toIndentedString(accuracy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

