/*
 * rata.digitraffic.fi
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information.  Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)    The service has a public Google-group [rail.digitraffic.fi](https://groups.google.com/forum/#!forum/rata_digitraffic_fi) for  communication between developers, service administrators and Fintraffic.  The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.    ### General notes of the API  * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946.  * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified  (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.digitraffic.traingraph.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * List of wagons used on this leg
 */
@JsonPropertyOrder({
  Wagon.JSON_PROPERTY_WAGON_TYPE,
  Wagon.JSON_PROPERTY_LOCATION,
  Wagon.JSON_PROPERTY_SALES_NUMBER,
  Wagon.JSON_PROPERTY_LENGTH,
  Wagon.JSON_PROPERTY_PLAYGROUND,
  Wagon.JSON_PROPERTY_PET,
  Wagon.JSON_PROPERTY_CATERING,
  Wagon.JSON_PROPERTY_VIDEO,
  Wagon.JSON_PROPERTY_LUGGAGE,
  Wagon.JSON_PROPERTY_SMOKING,
  Wagon.JSON_PROPERTY_DISABLED,
  Wagon.JSON_PROPERTY_VEHICLE_NUMBER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:31:03.368267+02:00[Europe/Helsinki]")
public class Wagon {
  public static final String JSON_PROPERTY_WAGON_TYPE = "wagonType";
  private String wagonType;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private Integer location;

  public static final String JSON_PROPERTY_SALES_NUMBER = "salesNumber";
  private Integer salesNumber;

  public static final String JSON_PROPERTY_LENGTH = "length";
  private Integer length;

  public static final String JSON_PROPERTY_PLAYGROUND = "playground";
  private Boolean playground;

  public static final String JSON_PROPERTY_PET = "pet";
  private Boolean pet;

  public static final String JSON_PROPERTY_CATERING = "catering";
  private Boolean catering;

  public static final String JSON_PROPERTY_VIDEO = "video";
  private Boolean video;

  public static final String JSON_PROPERTY_LUGGAGE = "luggage";
  private Boolean luggage;

  public static final String JSON_PROPERTY_SMOKING = "smoking";
  private Boolean smoking;

  public static final String JSON_PROPERTY_DISABLED = "disabled";
  private Boolean disabled;

  public static final String JSON_PROPERTY_VEHICLE_NUMBER = "vehicleNumber";
  private String vehicleNumber;

  public Wagon() {
  }

  public Wagon wagonType(String wagonType) {
    
    this.wagonType = wagonType;
    return this;
  }

   /**
   * Get wagonType
   * @return wagonType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WAGON_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWagonType() {
    return wagonType;
  }


  @JsonProperty(JSON_PROPERTY_WAGON_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWagonType(String wagonType) {
    this.wagonType = wagonType;
  }


  public Wagon location(Integer location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(Integer location) {
    this.location = location;
  }


  public Wagon salesNumber(Integer salesNumber) {
    
    this.salesNumber = salesNumber;
    return this;
  }

   /**
   * Wagon number in customer&#39;s ticket
   * @return salesNumber
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SALES_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSalesNumber() {
    return salesNumber;
  }


  @JsonProperty(JSON_PROPERTY_SALES_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSalesNumber(Integer salesNumber) {
    this.salesNumber = salesNumber;
  }


  public Wagon length(Integer length) {
    
    this.length = length;
    return this;
  }

   /**
   * Wagon length in centimeters
   * @return length
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLength() {
    return length;
  }


  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLength(Integer length) {
    this.length = length;
  }


  public Wagon playground(Boolean playground) {
    
    this.playground = playground;
    return this;
  }

   /**
   * Get playground
   * @return playground
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLAYGROUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPlayground() {
    return playground;
  }


  @JsonProperty(JSON_PROPERTY_PLAYGROUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlayground(Boolean playground) {
    this.playground = playground;
  }


  public Wagon pet(Boolean pet) {
    
    this.pet = pet;
    return this;
  }

   /**
   * Get pet
   * @return pet
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPet() {
    return pet;
  }


  @JsonProperty(JSON_PROPERTY_PET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPet(Boolean pet) {
    this.pet = pet;
  }


  public Wagon catering(Boolean catering) {
    
    this.catering = catering;
    return this;
  }

   /**
   * Get catering
   * @return catering
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CATERING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCatering() {
    return catering;
  }


  @JsonProperty(JSON_PROPERTY_CATERING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCatering(Boolean catering) {
    this.catering = catering;
  }


  public Wagon video(Boolean video) {
    
    this.video = video;
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VIDEO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVideo() {
    return video;
  }


  @JsonProperty(JSON_PROPERTY_VIDEO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideo(Boolean video) {
    this.video = video;
  }


  public Wagon luggage(Boolean luggage) {
    
    this.luggage = luggage;
    return this;
  }

   /**
   * Get luggage
   * @return luggage
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LUGGAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLuggage() {
    return luggage;
  }


  @JsonProperty(JSON_PROPERTY_LUGGAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLuggage(Boolean luggage) {
    this.luggage = luggage;
  }


  public Wagon smoking(Boolean smoking) {
    
    this.smoking = smoking;
    return this;
  }

   /**
   * Get smoking
   * @return smoking
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SMOKING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSmoking() {
    return smoking;
  }


  @JsonProperty(JSON_PROPERTY_SMOKING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmoking(Boolean smoking) {
    this.smoking = smoking;
  }


  public Wagon disabled(Boolean disabled) {
    
    this.disabled = disabled;
    return this;
  }

   /**
   * Get disabled
   * @return disabled
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisabled() {
    return disabled;
  }


  @JsonProperty(JSON_PROPERTY_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }


  public Wagon vehicleNumber(String vehicleNumber) {
    
    this.vehicleNumber = vehicleNumber;
    return this;
  }

   /**
   * Get vehicleNumber
   * @return vehicleNumber
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VEHICLE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVehicleNumber() {
    return vehicleNumber;
  }


  @JsonProperty(JSON_PROPERTY_VEHICLE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVehicleNumber(String vehicleNumber) {
    this.vehicleNumber = vehicleNumber;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Wagon wagon = (Wagon) o;
    return Objects.equals(this.wagonType, wagon.wagonType) &&
        Objects.equals(this.location, wagon.location) &&
        Objects.equals(this.salesNumber, wagon.salesNumber) &&
        Objects.equals(this.length, wagon.length) &&
        Objects.equals(this.playground, wagon.playground) &&
        Objects.equals(this.pet, wagon.pet) &&
        Objects.equals(this.catering, wagon.catering) &&
        Objects.equals(this.video, wagon.video) &&
        Objects.equals(this.luggage, wagon.luggage) &&
        Objects.equals(this.smoking, wagon.smoking) &&
        Objects.equals(this.disabled, wagon.disabled) &&
        Objects.equals(this.vehicleNumber, wagon.vehicleNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wagonType, location, salesNumber, length, playground, pet, catering, video, luggage, smoking, disabled, vehicleNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Wagon {\n");
    sb.append("    wagonType: ").append(toIndentedString(wagonType)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    salesNumber: ").append(toIndentedString(salesNumber)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    playground: ").append(toIndentedString(playground)).append("\n");
    sb.append("    pet: ").append(toIndentedString(pet)).append("\n");
    sb.append("    catering: ").append(toIndentedString(catering)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    luggage: ").append(toIndentedString(luggage)).append("\n");
    sb.append("    smoking: ").append(toIndentedString(smoking)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    vehicleNumber: ").append(toIndentedString(vehicleNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

